Repository netobserv/network-observability-console-plugin, pull requests merged in 2021-12, with the labels that each got.

#12 Update make for CI
  Makefile
  README.md
Labels: no-qe, lgtm, approved

#13 NETOBSERV-70: Create and display NetFlow table
  web/console-extensions.json
  web/locales/en/plugin__network-observability-plugin.json
  web/package-lock.json
  web/package.json
  web/src/api/loki.ts
  web/src/api/routes.ts
  web/src/components/__tests-data__/columns.tsx
  web/src/components/__tests-data__/flows.tsx
  web/src/components/__tests__/netflow-table-header.spec.tsx
  web/src/components/__tests__/netflow-table-row.spec.tsx
  web/src/components/__tests__/netflow-table.spec.tsx
  web/src/components/netflow-table-header.tsx
  web/src/components/netflow-table-row.tsx
  web/src/components/netflow-table.tsx
  web/src/components/netflow-traffic.tsx
  web/src/i18n.ts
  web/webpack.config.ts
Labels: no-qe, lgtm

#14 NETOBSERV-98: specify loki tenant id
  cmd/plugin-backend.go
  pkg/handler/loki.go
  pkg/httpclient/http_client.go
  pkg/server/routes.go
  pkg/server/server.go
  pkg/server/server_test.go
Labels: no-qe, lgtm, approved

#15 updated jest + react + enable style-loader
  web/package-lock.json
  web/package.json
  web/webpack.config.ts
Labels: no-qe, lgtm

#18 NETOBSERV-97 setup enzyme for react 17
  web/enzyme.config.ts
  web/package-lock.json
  web/package.json
  web/setup-tests.ts
Labels: no-qe, lgtm

#19 NETOBSERV-105 Netflow table sort test
  web/src/components/__tests-data__/flows.tsx
  web/src/components/__tests__/netflow-table-header.spec.tsx
  web/src/components/__tests__/netflow-table.spec.tsx
  web/src/components/netflow-table-row.tsx
Labels: no-qe, lgtm, approved

#20 Update doc, include testing instruction
  README.md
Labels: no-qe, lgtm, approved

#16 NETOBSERV-75 refresh dropdown + button
  web/locales/en/plugin__network-observability-plugin.json
  web/src/components/__tests-data__/extensions.tsx
  web/src/components/__tests__/netflow-traffic.spec.tsx
  web/src/components/__tests__/refresh-dropdown.spec.tsx
  web/src/components/netflow-traffic.css
  web/src/components/netflow-traffic.tsx
  web/src/components/refresh-dropdown.tsx
  web/src/utils/duration.tsx
  web/src/utils/poll-hook.ts
Labels: no-qe, lgtm

#21 NETOBSERV-79 Added ip addresses columns and special sorting for them
  web/src/components/netflow-table-header.tsx
  web/src/components/netflow-table-row.tsx
  web/src/components/netflow-table.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/__tests__/ip.spec.ts
  web/src/utils/ip.ts
Labels: no-qe, lgtm, approved

#22 Mocking react-i18next in tests
  web/setup-tests.ts
  web/src/components/__tests__/netflow-traffic.spec.tsx
Labels: no-qe, lgtm, approved

#17 NETOBSERV-71 added toolbar with select column modal
  web/locales/en/plugin__network-observability-plugin.json
  web/src/components/__tests-data__/columns.tsx
  web/src/components/__tests__/columns-modal.spec.tsx
  web/src/components/__tests__/netflow-traffic.spec.tsx
  web/src/components/columns-modal.css
  web/src/components/columns-modal.tsx
  web/src/components/netflow-table-header.tsx
  web/src/components/netflow-traffic.tsx
Labels: no-qe

#24 Add quay.io build badge
  README.md
Labels: no-qe, lgtm, approved

#25 NETOBSERV-119 Added port number resolution to IANA service name
  web/package-lock.json
  web/package.json
  web/src/components/netflow-table-row.tsx
  web/src/components/netflow-table.tsx
  web/src/utils/__tests__/port.spec.ts
  web/src/utils/port.ts
Labels: no-qe, lgtm, approved

#26 Frontend formatting
  Dockerfile
  Makefile
  web/.eslintrc.js
  web/.prettierrc.json
  web/package-lock.json
  web/package.json
  web/src/api/loki.ts
  web/src/api/routes.ts
  web/src/components/__tests-data__/columns.tsx
  web/src/components/__tests-data__/extensions.tsx
  web/src/components/__tests-data__/flows.tsx
  web/src/components/__tests__/columns-modal.spec.tsx
  web/src/components/__tests__/netflow-table-header.spec.tsx
  web/src/components/__tests__/netflow-table-row.spec.tsx
  web/src/components/__tests__/netflow-table.spec.tsx
  web/src/components/__tests__/netflow-traffic.spec.tsx
  web/src/components/__tests__/refresh-dropdown.spec.tsx
  web/src/components/columns-modal.tsx
  web/src/components/netflow-table-header.tsx
  web/src/components/netflow-table-row.tsx
  web/src/components/netflow-table.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/refresh-dropdown.tsx
  web/src/i18n.ts
  web/src/utils/__tests__/ip.spec.ts
  web/src/utils/__tests__/port.spec.ts
  web/src/utils/duration.tsx
  web/src/utils/ip.ts
  web/src/utils/port.ts
Labels: no-qe, lgtm, approved

#27 Fix dockerfile
  Dockerfile
Labels: no-qe, lgtm, approved

#28 NETOBSERV-119 Changed port sort behavior to have numerical port last
  web/src/components/netflow-table.tsx
  web/src/utils/__tests__/port.spec.ts
  web/src/utils/port.ts
Labels: no-qe, lgtm, approved

#30 Fixing ip addresses initialisaton
  web/locales/en/plugin__network-observability-plugin.json
  web/src/components/netflow-traffic.tsx
Labels: no-qe, lgtm, approved
