Repository netobserv/network-observability-console-plugin, pull requests merged in 2022-11, with the labels that each got.

#225 Updated mocks
  mocks/loki/flows.json
  mocks/loki/namespaces.json
  mocks/loki/topology.json
  mocks/loki/topology_app.json
  mocks/loki/topology_host.json
  mocks/loki/topology_namespace.json
  mocks/loki/topology_owner.json
  mocks/loki/topology_resource.json
  mocks/updateMocks.sh
  pkg/handler/lokiclientmock/loki_client_mock.go
Labels: lgtm, approved

#223 Make RecordField resilient to NaN values in time fields
  web/src/components/netflow-record/record-field.tsx
Labels: lgtm, approved

#222 NETOBSERV-636 UI Consistency: Overview styling
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/metrics/__tests__/metrics-content.spec.tsx
  web/src/components/metrics/metrics-content.css
  web/src/components/metrics/metrics-content.tsx
  web/src/components/metrics/metrics-helper.tsx
  web/src/components/metrics/metrics-total-content.tsx
  web/src/components/metrics/stat-donut.tsx
  web/src/components/netflow-overview/__tests__/netflow-overview-panel.spec.tsx
  web/src/components/netflow-overview/netflow-overview-panel.css
  web/src/components/netflow-overview/netflow-overview-panel.tsx
  web/src/components/netflow-overview/netflow-overview.css
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-overview/panel-kebab.css
  web/src/components/netflow-overview/panel-kebab.tsx
  web/src/components/netflow-table/netflow-table-row.tsx
  web/src/components/netflow-table/netflow-table.css
  web/src/components/netflow-table/netflow-table.tsx
  web/src/components/netflow-topology/element-panel.css
  web/src/components/netflow-topology/element-panel.tsx
  web/src/components/netflow-traffic.css
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/__tests__/query-summary.spec.tsx
  web/src/components/query-summary/query-summary.css
  web/src/components/query-summary/query-summary.tsx
  web/src/utils/theme-hook.ts
  web/src/utils/theme.ts
Labels: lgtm, approved, ok-to-test

#214 NETOBSERV-634 UI Consistency: Side panel styling
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/metrics/metrics-content.tsx
  web/src/components/netflow-record/record-panel.css
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-topology/__tests__/element-panel.spec.tsx
  web/src/components/netflow-topology/element-panel.css
  web/src/components/netflow-topology/element-panel.tsx
  web/src/components/netflow-traffic.tsx
Labels: lgtm, approved, ok-to-test

#227 NETOBSERV-656 follow-up: add chart tooltips
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/modals/overview-panels-modal.tsx
  web/src/components/netflow-overview/netflow-overview-panel.css
  web/src/components/netflow-overview/netflow-overview-panel.tsx
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-overview/panel-kebab.tsx
  web/src/utils/overview-panels.ts
Labels: lgtm, approved, ok-to-test

#231 NETOBSERV-701 Cardinality panel: Namespaces listed twice
  web/src/components/query-summary/summary-panel.tsx
Labels: lgtm, approved

#215 NETOBSERV-635 UI Consistency: Tabs options
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/__tests__/netflow-traffic.spec.tsx
  web/src/components/dropdowns/__tests__/display-dropdown.spec.tsx
  web/src/components/dropdowns/__tests__/table-display-dropdown.spec.tsx
  web/src/components/dropdowns/display-dropdown.tsx
  web/src/components/dropdowns/group-dropdown.tsx
  web/src/components/dropdowns/layout-dropdown.tsx
  web/src/components/dropdowns/overview-display-dropdown.css
  web/src/components/dropdowns/overview-display-dropdown.tsx
  web/src/components/dropdowns/query-options-dropdown.tsx
  web/src/components/dropdowns/table-display-dropdown.css
  web/src/components/dropdowns/table-display-dropdown.tsx
  web/src/components/dropdowns/topology-display-dropdown.css
  web/src/components/dropdowns/topology-display-dropdown.tsx
  web/src/components/dropdowns/truncate-dropdown.tsx
  web/src/components/netflow-record/__tests__/record-field.spec.tsx
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-table/__tests__/netflow-table-row.spec.tsx
  web/src/components/netflow-table/__tests__/netflow-table.spec.tsx
  web/src/components/netflow-table/netflow-table-row.tsx
  web/src/components/netflow-table/netflow-table.tsx
  web/src/components/netflow-topology/__tests__/netflow-topology.spec.tsx
  web/src/components/netflow-topology/__tests__/options-panel.spec.tsx
  web/src/components/netflow-topology/netflow-topology.css
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-topology/options-panel.css
  web/src/components/netflow-topology/options-panel.tsx
  web/src/components/netflow-traffic.css
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/summary-panel.tsx
  web/src/components/search/search.tsx
  web/src/utils/errors.ts
  web/src/utils/local-storage-hook.ts
Labels: lgtm, approved

#224 NETOBSERV-637 UI Consistency: Topology styling
  web/locales/en/plugin__netobserv-plugin.json
  web/package-lock.json
  web/package.json
  web/src/components/netflow-topology/components/edge.tsx
  web/src/components/netflow-topology/components/node.tsx
  web/src/components/netflow-topology/netflow-topology.css
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-topology/styles/styleNode.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/topology.ts
Labels: lgtm, approved

#226 NETOBSERV-602 Fix query stats computed for topology
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/__tests__/flows-query-summary.spec.tsx
  web/src/components/query-summary/__tests__/metrics-query-summary.spec.tsx
  web/src/components/query-summary/flows-query-summary.tsx
  web/src/components/query-summary/metrics-query-summary.tsx
  web/src/components/query-summary/summary-panel.tsx
Labels: approved

#232 NETOBSERV-619: adding deduplication filter to topology endpoint
  pkg/loki/flow_query.go
  pkg/loki/topology_query.go
  pkg/server/server_test.go
Labels: lgtm

#229 NETOBSERV-699 redundant charts: hide some by default
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/__tests-data__/panels.ts
  web/src/components/modals/overview-panels-modal.tsx
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/utils/features-gate.ts
  web/src/utils/overview-panels.ts
Labels: lgtm, approved, ok-to-test

#235 Fix "time range in seconds" calculation in flow query stats
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/flows-query-summary.tsx
  web/src/model/topology.ts
Labels: lgtm, approved, ok-to-test

#230 Fix mocks
  Makefile
  pkg/handler/topology.go
  pkg/model/loki.go
  pkg/model/loki_test.go
  web/src/api/loki.ts
  web/src/api/routes.ts
  web/src/utils/metrics.ts
Labels: lgtm, approved

#239 NETOBSERV-688 UI: Overview labels options
  web/src/components/dropdowns/__tests__/truncate-dropdown.spec.tsx
  web/src/components/dropdowns/overview-display-dropdown.tsx
  web/src/components/dropdowns/topology-display-dropdown.tsx
  web/src/components/dropdowns/truncate-dropdown.tsx
  web/src/components/metrics/metrics-content.css
  web/src/components/metrics/metrics-content.tsx
  web/src/components/metrics/metrics-helper.tsx
  web/src/components/metrics/metrics-total-content.tsx
  web/src/components/metrics/stat-donut.tsx
  web/src/components/netflow-overview/__tests__/netflow-overview.spec.tsx
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-topology/__tests__/element-panel.spec.tsx
  web/src/components/netflow-topology/element-panel.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/topology.ts
  web/src/utils/local-storage-hook.ts
Labels: lgtm, approved

#244 Speed up docker build time
  Dockerfile
  Makefile
Labels: lgtm, approved

#236 NETOBSERV-608 UI: Reorder columns in flow table
  web/src/components/netflow-table/__tests__/netflow-table-header.spec.tsx
  web/src/components/netflow-table/__tests__/netflow-table.spec.tsx
  web/src/components/netflow-table/netflow-table-header.css
  web/src/components/netflow-table/netflow-table-header.tsx
  web/src/components/netflow-table/netflow-table.tsx
  web/src/components/netflow-traffic.tsx
Labels: lgtm, approved, ok-to-test

#240 NETOBSERV-662 UI Consistency: Dropdown labels
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/filters/filters-toolbar.tsx
  web/src/components/netflow-traffic.css
  web/src/components/netflow-traffic.tsx
Labels: lgtm, approved, ok-to-test

#241 NETOBSERV-685 3D option behind feature gate
  web/src/components/dropdowns/layout-dropdown.tsx
  web/src/components/netflow-topology/2d/componentFactories/componentFactory.ts
  web/src/components/netflow-topology/2d/componentFactories/shapesComponentFactory.ts
  web/src/components/netflow-topology/2d/componentFactories/stylesComponentFactory.tsx
  web/src/components/netflow-topology/2d/components/edge.tsx
  web/src/components/netflow-topology/2d/components/node.tsx
  web/src/components/netflow-topology/2d/layouts/layoutFactory.ts
  web/src/components/netflow-topology/2d/styles/styleEdge.tsx
  web/src/components/netflow-topology/2d/styles/styleGroup.tsx
  web/src/components/netflow-topology/2d/styles/styleNode.tsx
  web/src/components/netflow-topology/2d/topology-content.css
  web/src/components/netflow-topology/2d/topology-content.tsx
  web/src/components/netflow-topology/3d/three-d-topology-content.tsx
  web/src/components/netflow-topology/__tests__/netflow-topology.spec.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/model/topology.ts
  web/src/utils/features-gate.ts
Labels: lgtm, approved

#245 Follow-up on #239: do not truncate on tooltips..
  web/src/api/loki.ts
  web/src/components/metrics/__tests__/metrics-content.spec.tsx
  web/src/components/metrics/__tests__/stat-donut.spec.tsx
  web/src/components/metrics/metrics-content.tsx
  web/src/components/metrics/metrics-helper.tsx
  web/src/components/metrics/metrics-total-content.tsx
  web/src/components/metrics/stat-donut.tsx
  web/src/components/netflow-overview/__tests__/netflow-overview-panel.spec.tsx
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-topology/element-panel.tsx
Labels: approved

#246 NETOBSERV-474 summary filters by source or dest
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/loki.ts
  web/src/components/filters/summary-filter-button.css
  web/src/components/filters/summary-filter-button.tsx
  web/src/components/metrics/metrics-helper.tsx
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-topology/2d/styles/styleNode.tsx
  web/src/components/netflow-topology/2d/topology-content.tsx
  web/src/components/netflow-topology/__tests__/element-panel.spec.tsx
  web/src/components/netflow-topology/element-field.tsx
  web/src/components/netflow-topology/element-fields.tsx
  web/src/components/netflow-topology/element-panel.tsx
  web/src/components/netflow-topology/peer-resource-link.tsx
  web/src/components/query-summary/summary-panel.tsx
  web/src/model/topology.ts
  web/src/utils/__tests__/metrics.spec.ts
  web/src/utils/ids.ts
  web/src/utils/metrics.ts
Labels: approved
