Repository netobserv/network-observability-console-plugin, pull requests merged in 2022-09, with the labels that each got.

#185 Add breaking-change triage in release notes
  .github/release.yml
Labels: lgtm, approved

#191 NETOBSERV-433 and NETOBSERV-373 - unify names
  Makefile
  mocks/updateMocks.sh
  web/console-extensions.json
  web/cypress/support/const.js
  web/i18next-parser.config.js
  web/locales/en/plugin__netobserv-plugin.json
  web/package-lock.json
  web/package.json
  web/src/components/dropdowns/display-dropdown.tsx
  web/src/components/dropdowns/group-dropdown.tsx
  web/src/components/dropdowns/layout-dropdown.tsx
  web/src/components/dropdowns/metric-function-dropdown.tsx
  web/src/components/dropdowns/metric-type-dropdown.tsx
  web/src/components/dropdowns/query-options-dropdown.tsx
  web/src/components/dropdowns/refresh-dropdown.tsx
  web/src/components/dropdowns/scope-dropdown.tsx
  web/src/components/dropdowns/time-range-dropdown.tsx
  web/src/components/dropdowns/truncate-dropdown.tsx
  web/src/components/filters/filter-hints.tsx
  web/src/components/filters/filters-dropdown.tsx
  web/src/components/filters/filters-toolbar.tsx
  web/src/components/messages/loki-error.tsx
  web/src/components/modals/columns-modal.tsx
  web/src/components/modals/export-modal.tsx
  web/src/components/modals/time-range-modal.tsx
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-tab.tsx
  web/src/components/netflow-table/netflow-table.tsx
  web/src/components/netflow-topology/element-panel.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-topology/options-panel.tsx
  web/src/components/netflow-topology/styles/styleNode.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/query-summary.tsx
  web/src/components/query-summary/summary-panel.tsx
  web/src/i18n.ts
  web/src/index.tsx
  web/src/utils/context.ts
  web/src/utils/local-storage-hook.ts
Labels: lgtm, approved

#192 NETOBSERV-581 - grouping for Nodes+NS broken
  web/src/components/netflow-topology/element-panel.tsx
  web/src/model/topology.ts
Labels: lgtm, approved, ok-to-test

#193 NETOBSERV-554 - Topology test ids generation
  web/src/model/topology.ts
  web/src/utils/ids.ts
Labels: approved

#196 NETOBSERV-581 & NETOBSERV-554 fix group id
  web/src/model/topology.ts
  web/src/utils/ids.ts
Labels: lgtm, approved
