Repository netobserv/network-observability-console-plugin, pull requests merged in 2022-10, with the labels that each got.

#190 NETOBSERV-408 Top X charts
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/loki.ts
  web/src/components/__tests-data__/panels.ts
  web/src/components/dropdowns/query-options-dropdown.tsx
  web/src/components/messages/loki-error.tsx
  web/src/components/metrics/__tests__/metrics-content.spec.tsx
  web/src/components/metrics/metrics-content.css
  web/src/components/metrics/metrics-content.tsx
  web/src/components/modals/overview-panels-modal.tsx
  web/src/components/netflow-overview/__tests__/netflow-overview-panel.spec.tsx
  web/src/components/netflow-overview/__tests__/netflow-overview.spec.tsx
  web/src/components/netflow-overview/netflow-overview-panel.css
  web/src/components/netflow-overview/netflow-overview-panel.tsx
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-topology/element-panel.css
  web/src/components/netflow-topology/element-panel.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/overview-panels.ts
Labels: lgtm, approved, ok-to-test

#198 NETOBSERV-489: Added an option to forward user token to loki
  cmd/plugin-backend.go
  pkg/handler/export.go
  pkg/handler/flows.go
  pkg/handler/loki.go
  pkg/handler/resources.go
  pkg/handler/topology.go
  pkg/loki/config.go
  pkg/loki/query_test.go
  pkg/server/server_flows_test.go
Labels: lgtm

#197 NETOBSERV-586 - Console plugin dependencies update
  web/locales/en/plugin__netobserv-plugin.json
  web/moduleMapper/dummy.tsx
  web/package-lock.json
  web/package.json
  web/setup-tests.tsx
  web/src/components/dropdowns/layout-dropdown.tsx
  web/src/components/modals/modal.tsx
  web/src/components/modals/time-range-modal.css
  web/src/components/modals/time-range-modal.tsx
  web/src/components/netflow-record/__tests__/record-field.spec.tsx
  web/src/components/netflow-record/record-field.css
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-table/__tests__/netflow-table.spec.tsx
  web/src/components/netflow-table/netflow-table-row.tsx
  web/src/components/netflow-topology/componentFactories/stylesComponentFactory.tsx
  web/src/components/netflow-topology/components/edge.tsx
  web/src/components/netflow-topology/components/node.tsx
  web/src/components/netflow-topology/layouts/layoutFactory.ts
  web/src/components/netflow-topology/netflow-topology.css
  web/src/components/netflow-topology/styles/styleEdge.tsx
  web/src/components/netflow-topology/styles/styleGroup.tsx
  web/src/components/netflow-topology/styles/styleNode.tsx
  web/src/model/topology.ts
Labels: approved, ok-to-test

#195 NETOBSERV-602 Fix computed metrics
  Makefile
  pkg/handler/topology.go
  pkg/loki/topology_query.go
  pkg/server/server_test.go
  web/cypress/integration/table/table.spec.js
  web/cypress/support/commands.js
  web/cypress/support/const.js
  web/locales/en/plugin__netobserv-plugin.json
  web/setup-tests.tsx
  web/src/api/loki.ts
  web/src/api/routes.ts
  web/src/components/__tests-data__/metrics.ts
  web/src/components/dropdowns/__tests__/metric-function-dropdown.spec.tsx
  web/src/components/dropdowns/__tests__/metric-type-dropdown.spec.tsx
  web/src/components/dropdowns/metric-function-dropdown.tsx
  web/src/components/dropdowns/metric-type-dropdown.tsx
  web/src/components/metrics/__tests__/metrics-content.spec.tsx
  web/src/components/metrics/metrics-content.tsx
  web/src/components/netflow-overview/netflow-overview-panel.tsx
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-topology/__tests-data__/metrics.ts
  web/src/components/netflow-topology/__tests__/element-panel.spec.tsx
  web/src/components/netflow-topology/componentFactories/componentFactory.ts
  web/src/components/netflow-topology/componentFactories/shapesComponentFactory.ts
  web/src/components/netflow-topology/componentFactories/stylesComponentFactory.tsx
  web/src/components/netflow-topology/components/node.tsx
  web/src/components/netflow-topology/element-panel.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-topology/styles/styleNode.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/query-summary.tsx
  web/src/model/flow-query.ts
  web/src/model/metrics.ts
  web/src/model/topology.ts
  web/src/utils/__tests__/metrics.spec.ts
  web/src/utils/bytes.ts
  web/src/utils/count.ts
  web/src/utils/datetime.ts
  web/src/utils/metrics.ts
  web/src/utils/panel.ts
  web/src/utils/router.ts
Labels: lgtm, approved

#199 NETOBSERV-487 - deselecting "Export all datas" causes few columns to be missed
  pkg/handler/csv/loki_csv.go
  web/src/components/netflow-traffic.tsx
Labels: lgtm, approved, ok-to-test

#204 NETOBSERV-506 loki config url style
  web/src/components/messages/loki-error.tsx
Labels: no-qe, lgtm, approved

#203 NETOBSERV-409 - Total flows chart
  cmd/plugin-backend.go
  pkg/loki/topology_query.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/metrics/metrics-content.tsx
  web/src/components/netflow-overview/__tests__/netflow-overview-panel.spec.tsx
  web/src/components/netflow-overview/__tests__/netflow-overview.spec.tsx
  web/src/components/netflow-overview/netflow-overview-panel.tsx
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/__tests__/query-summary.spec.tsx
  web/src/components/query-summary/__tests__/summary-panel.spec.tsx
  web/src/components/query-summary/query-summary.tsx
  web/src/components/query-summary/summary-panel.tsx
  web/src/model/flow-query.ts
Labels: lgtm, approved

#206 NETOBSERV-516 explicit limit reached message
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/query-summary/query-summary.tsx
  web/src/components/query-summary/summary-panel.css
  web/src/components/query-summary/summary-panel.tsx
  web/src/utils/bytes.ts
Labels: lgtm, approved

#207 Fix Too much recursion error
  web/src/components/dropdowns/group-dropdown.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/topology.ts
Labels: lgtm, approved

#209 Fix cases where filter button didn't work well
  pkg/loki/topology_query.go
  web/src/components/netflow-topology/element-panel.tsx
Labels: lgtm, approved

#212 NETOBSERV-650 Top X value is incorrect at first time
  web/src/components/netflow-traffic-parent.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/local-storage-hook.ts
  web/src/utils/router.ts
  web/src/utils/url.ts
Labels: lgtm, approved, ok-to-test

#210 NETOBSERV-656 overview page changes and additions
  pkg/handler/flows.go
  pkg/handler/flows_test.go
  pkg/handler/resources.go
  pkg/handler/topology.go
  pkg/loki/filter.go
  pkg/loki/flow_query.go
  pkg/loki/matrix_merger.go
  pkg/loki/matrix_merger_test.go
  pkg/loki/query_test.go
  pkg/loki/topology_query.go
  pkg/model/filters/filters.go
  pkg/model/filters/filters_test.go
  pkg/utils/constants/constants.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/loki.ts
  web/src/components/metrics/__tests__/metrics-content.spec.tsx
  web/src/components/metrics/__tests__/stat-donut.spec.tsx
  web/src/components/metrics/metrics-content.tsx
  web/src/components/metrics/metrics-helper.tsx
  web/src/components/metrics/metrics-total-content.tsx
  web/src/components/metrics/stat-donut.tsx
  web/src/components/netflow-overview/__tests__/netflow-overview-panel.spec.tsx
  web/src/components/netflow-overview/__tests__/netflow-overview.spec.tsx
  web/src/components/netflow-overview/netflow-overview-panel.tsx
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-overview/panel-kebab.tsx
  web/src/components/netflow-topology/__tests__/element-panel.spec.tsx
  web/src/components/netflow-topology/element-panel.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/query-summary.tsx
  web/src/model/__tests__/flow-query.spec.ts
  web/src/model/filters.ts
  web/src/model/flow-query.ts
  web/src/model/resource.ts
  web/src/utils/__tests__/metrics.spec.ts
  web/src/utils/bytes.ts
  web/src/utils/count.ts
  web/src/utils/filter-definitions.ts
  web/src/utils/format.ts
  web/src/utils/metrics.ts
  web/src/utils/overview-panels.ts
Labels: lgtm, approved

#213 Increase loki default timeout
  cmd/plugin-backend.go
Labels: lgtm, approved

#217 Fix parenthesis in help message
  cmd/plugin-backend.go
Labels: lgtm, approved

#218 Update README.md
  README.md
Labels: lgtm, approved

#221 Define the SHELL variable in the Makefile
  Makefile
Labels: lgtm, approved

#219 NETOBSERV-648 Put unimplemented panels behind feature gates
  web/src/components/__tests__/netflow-traffic.spec.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/overview-panels.ts
Labels: lgtm, approved

#220 NETOBSERV-414 change clipboard copy components to read only
  web/src/components/netflow-record/record-panel.tsx
Labels: lgtm, approved, ok-to-test
