Repository netobserv/network-observability-console-plugin, pull requests merged in 2022-12, with the labels that each got.

#247 NETOBSERV-686 3D view implementation
  Dockerfile
  web/package-lock.json
  web/package.json
  web/src/components/netflow-topology/3d/three-d-topology-content.css
  web/src/components/netflow-topology/3d/three-d-topology-content.tsx
  web/webpack.config.ts
  web/webpack.standalone.ts
Labels: lgtm, approved

#237 NETOBSERV-621 split summary metrics, limit 5 per chart
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/metrics/__tests__/metrics-content.spec.tsx
  web/src/components/metrics/metrics-content.tsx
  web/src/components/netflow-topology/__tests__/element-panel.spec.tsx
  web/src/components/netflow-topology/element-panel-metrics.tsx
  web/src/components/netflow-topology/element-panel-stats.tsx
  web/src/components/netflow-topology/element-panel.css
  web/src/components/netflow-topology/element-panel.tsx
  web/src/components/netflow-traffic.tsx
Labels: lgtm, approved

#243 NETOBSERV-698 add ability to show/hide filter chips
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/filters/filters-toolbar.tsx
  web/src/utils/local-storage-hook.ts
Labels: lgtm, approved

#238 NETOBSERV-609 UI: Resize a column in flow table
  web/src/components/modals/__tests__/columns-modal.spec.tsx
  web/src/components/modals/columns-modal.tsx
  web/src/components/netflow-table/__tests__/netflow-table-header.spec.tsx
  web/src/components/netflow-table/__tests__/netflow-table.spec.tsx
  web/src/components/netflow-table/netflow-table-header.css
  web/src/components/netflow-table/netflow-table-header.tsx
  web/src/components/netflow-table/netflow-table.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/columns.ts
  web/src/utils/local-storage-hook.ts
Labels: lgtm, approved, ok-to-test

#252 NETOBSERV-671 UI: Fields / Overview tooltips
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/netflow-record/record-panel.css
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-table/netflow-table-header.tsx
  web/src/utils/columns.ts
  web/src/utils/overview-panels.ts
Labels: lgtm, approved

#254 [4.12] NETOBSERV-671 backport
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/netflow-record/record-panel.css
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-table/netflow-table-header.tsx
  web/src/utils/columns.ts
  web/src/utils/overview-panels.ts
Labels: lgtm

#258 Bug NETOBSERV-743: update build image & CI tests to Go 1.18 (release-4.12)
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  .golangci.yml
  Dockerfile
Labels: lgtm, approved

#257 NETOBSERV-743: update build image & CI tests to Go 1.18
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  .golangci.yml
  Dockerfile
Labels: lgtm, approved

#260 [4.12 backport] Bump qs and express in /web (#256)
  web/package-lock.json
Labels: lgtm, approved

#251 NETOBSERV-723 Extra URL request made in Console Plugin
  web/src/api/routes.ts
  web/src/utils/context.ts
Labels: lgtm, approved

#261 NETOBSERV-700 UI freeze when client date is after server date
  pkg/handler/topology.go
  pkg/model/loki.go
  pkg/model/loki_test.go
  web/src/api/loki.ts
  web/src/api/routes.ts
  web/src/components/__tests-data__/metrics.ts
  web/src/components/netflow-topology/__tests-data__/metrics.ts
  web/src/utils/__tests__/metrics.spec.ts
  web/src/utils/metrics.ts
Labels: lgtm, approved, ok-to-test

#262 NETOBSERV-700 Backport
  pkg/handler/topology.go
  pkg/model/loki.go
  pkg/model/loki_test.go
  web/src/api/loki.ts
  web/src/api/routes.ts
  web/src/components/__tests-data__/metrics.ts
  web/src/components/netflow-topology/__tests-data__/metrics.ts
  web/src/utils/__tests__/metrics.spec.ts
  web/src/utils/metrics.ts
Labels: lgtm, approved

#265 Add Steven as a maintainer
  OWNERS
Labels: lgtm, approved

#263 NETOBSERV-741 "Clear all filters" setting is reset back to default when switching panels
  web/src/components/netflow-traffic.tsx
  web/src/utils/router.ts
Labels: lgtm, approved

#264 NETOBSERV-741 Backport
  web/src/components/netflow-traffic.tsx
  web/src/utils/router.ts
Labels: lgtm, approved
