Repository netobserv/network-observability-console-plugin, pull requests merged in 2022-04, with the labels that each got.

#102 NETOBSERV-126: Added service name configuration
  cmd/plugin-backend.go
  pkg/handler/frontend-config.go
  pkg/server/routes.go
  pkg/server/server.go
  web/.eslintrc.js
  web/console-extensions.json
  web/package.json
  web/src/api/routes.ts
  web/src/components/__tests__/netflow-traffic.spec.tsx
  web/src/components/filters-toolbar.tsx
  web/src/components/netflow-tab.tsx
  web/src/components/netflow-traffic-parent.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/config.ts
  web/src/utils/__tests__/port.spec.ts
  web/src/utils/config.ts
  web/src/utils/filters.ts
  web/src/utils/port.ts
Labels: lgtm, approved

#106 Fix warning in test
  web/setup-tests.ts
  web/src/components/__tests__/netflow-traffic.spec.tsx
  web/src/utils/__tests__/port.spec.ts
  web/src/utils/config.ts
Labels: lgtm, approved

#107 NETOBSERV-218 upgrade base image
  Dockerfile
Labels: lgtm, approved, ok-to-test

#97 NETOBSERV-230 topology view
  web/locales/en/plugin__network-observability-plugin.json
  web/package-lock.json
  web/package.json
  web/src/components/dropdowns/layout-dropdown.tsx
  web/src/components/netflow-topology/__tests-data__/metrics.ts
  web/src/components/netflow-topology/__tests__/netflow-topology.spec.tsx
  web/src/components/netflow-topology/componentFactories/componentFactory.ts
  web/src/components/netflow-topology/componentFactories/shapesComponentFactory.ts
  web/src/components/netflow-topology/componentFactories/stylesComponentFactory.tsx
  web/src/components/netflow-topology/layouts/layoutFactory.ts
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-topology/options-panel.tsx
  web/src/components/netflow-topology/styles/styleEdge.tsx
  web/src/components/netflow-topology/styles/styleGroup.tsx
  web/src/components/netflow-topology/styles/styleNode.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/topology.ts
  web/src/utils/bytes.ts
  web/src/utils/label.ts
Labels: lgtm

#108 NETOBSERV-217 Show summary of filtered data in NetFlow table
  web/locales/en/plugin__network-observability-plugin.json
  web/setup-tests.ts
  web/src/components/netflow-traffic.css
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/__tests__/query-summary.spec.tsx
  web/src/components/query-summary/__tests__/summary-panel.spec.tsx
  web/src/components/query-summary/query-summary.css
  web/src/components/query-summary/query-summary.tsx
  web/src/components/query-summary/summary-panel.css
  web/src/components/query-summary/summary-panel.tsx
Labels: lgtm

#116 NETOBSERV-273 Reducing empty array with no initial value
  web/src/components/query-summary/query-summary.tsx
  web/src/components/query-summary/summary-panel.tsx
Labels: lgtm

#117 NETOBSERV-278 Rename Address to IP
  web/locales/en/plugin__network-observability-plugin.json
  web/src/utils/columns.ts
  web/src/utils/filter-definitions.ts
Labels: lgtm, approved

#118 NETOBSERV-269 Port exact match
  pkg/loki/flow_query.go
  pkg/server/server_flows_test.go
Labels: lgtm, approved

#113 NETOBSERV-244 Topology Export
  web/package-lock.json
  web/package.json
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/typedefs/save-svg-as-png.d.ts
Labels: lgtm

#114 NETOBSERV-235 Topology quick filtering
  web/locales/en/plugin__network-observability-plugin.json
  web/src/components/netflow-topology/__tests__/netflow-topology.spec.tsx
  web/src/components/netflow-topology/netflow-topology.css
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-topology/styles/styleNode.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/topology.ts
Labels: lgtm

#115 NETOBSERV-241 Topology extra groups
  pkg/loki/topology_query.go
  pkg/server/server_test.go
  web/locales/en/plugin__network-observability-plugin.json
  web/src/api/loki.ts
  web/src/components/dropdowns/__tests__/group-dropdown.spec.tsx
  web/src/components/dropdowns/group-dropdown.tsx
  web/src/components/netflow-topology/styles/styleNode.tsx
  web/src/model/topology.ts
Labels: lgtm

#119 Fix linefilter regex, disallowing '"' in before-match
  pkg/loki/flow_query.go
  pkg/server/server_flows_test.go
Labels: lgtm, approved

#111 NETOBSERV-240 Topology metric selection
  pkg/handler/topology.go
  pkg/loki/topology_query.go
  web/locales/en/plugin__network-observability-plugin.json
  web/src/api/loki.ts
  web/src/api/routes.ts
  web/src/components/dropdowns/__tests__/metric-function-dropdown.spec.tsx
  web/src/components/dropdowns/__tests__/metric-type-dropdown.spec.tsx
  web/src/components/dropdowns/metric-function-dropdown.tsx
  web/src/components/dropdowns/metric-type-dropdown.tsx
  web/src/components/netflow-topology/__tests__/netflow-topology.spec.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/flow-query.ts
  web/src/model/topology.ts
  web/src/utils/count.ts
  web/src/utils/router.ts
  web/src/utils/url.ts
Labels: lgtm

#122 NETOBSERV-288 - conditionnal rendering to improve perfs on table
  web/src/components/netflow-record/record-field.css
  web/src/components/netflow-table/__tests__/netflow-table-row.spec.tsx
  web/src/components/netflow-table/netflow-table-header.tsx
  web/src/components/netflow-table/netflow-table-row.tsx
  web/src/components/netflow-table/netflow-table.css
  web/src/components/netflow-table/netflow-table.tsx
  web/src/components/netflow-traffic.css
Labels: lgtm

#110 NETOBSERV-232 Topology selection
  web/locales/en/plugin__network-observability-plugin.json
  web/package-lock.json
  web/package.json
  web/src/components/netflow-topology/__tests-data__/metrics.ts
  web/src/components/netflow-topology/__tests__/element-panel.spec.tsx
  web/src/components/netflow-topology/__tests__/netflow-topology.spec.tsx
  web/src/components/netflow-topology/element-panel.css
  web/src/components/netflow-topology/element-panel.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/datetime.ts
Labels: lgtm

#129 NETOBSERV-279 fix issues with filters on nodes
  pkg/handler/flows.go
  pkg/handler/loki.go
  pkg/handler/resources.go
  pkg/handler/resources_test.go
  pkg/handler/topology.go
  pkg/httpclient/http_client.go
  pkg/httpclient/httpclienttest/http_client_mock.go
  pkg/server/routes.go
  web/src/api/routes.ts
  web/src/model/__tests__/resource.spec.ts
  web/src/model/resource.ts
  web/src/utils/__tests__/label.spec.ts
  web/src/utils/label.ts
Labels: lgtm, approved

#126 NETOBSERV-272 - NETOBSERV-274 - Query protocols & stats, port names
  web/src/components/query-summary/summary-panel.tsx
Labels: lgtm

#130 NETOBSERV-240 merge fix
  web/src/components/netflow-topology/element-panel.tsx
  web/src/components/netflow-traffic.tsx
Labels: lgtm

#125 NETOBSERV-275 Stats panel: make number of bytes more human-friendly
  web/locales/en/plugin__network-observability-plugin.json
  web/src/components/query-summary/__tests__/query-summary.spec.tsx
  web/src/components/query-summary/query-summary.tsx
Labels: lgtm

#132 Update base image to recommended (fixed vulns)
  Dockerfile
Labels: lgtm, approved, ok-to-test

#133 NETOBSERV-270 resizable panel
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-topology/element-panel.tsx
  web/src/components/netflow-topology/options-panel.tsx
  web/src/components/netflow-traffic.css
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/summary-panel.tsx
  web/src/utils/panel.tsx
Labels: lgtm

#137 NETOBSERV-322 Sort crash on common columns
  web/src/utils/columns.ts
Labels: lgtm

#135 NETOBSERV-321 query stats panels crashes netflow-traffic page
  web/src/components/query-summary/summary-panel.tsx
Labels: lgtm, ok-to-test

#138 NETOBSERV-278 Rename address to IP (next)
  web/locales/en/plugin__network-observability-plugin.json
  web/src/components/dropdowns/refresh-dropdown.tsx
  web/src/components/filters/__tests__/filters-toolbar.spec.tsx
  web/src/components/netflow-topology/__tests__/element-panel.spec.tsx
  web/src/components/netflow-topology/element-panel.tsx
  web/src/components/netflow-topology/styles/styleNode.tsx
  web/src/components/query-summary/__tests__/summary-panel.spec.tsx
  web/src/components/query-summary/summary-panel.tsx
  web/src/utils/columns.ts
  web/src/utils/datetime.ts
  web/src/utils/filter-definitions.ts
Labels: lgtm, approved

#134 NETOBSERV-293 Topology: Expand groups crash after refresh
  web/src/components/netflow-topology/__tests__/netflow-topology.spec.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/topology.ts
Labels: lgtm
