Repository netobserv/network-observability-console-plugin, pull requests merged in 2022-03, with the labels that each got.

#89 Add new approvers
  OWNERS
Labels: no-qe, lgtm, approved

#87 NETOBSERV-176 regex case insensitive
  pkg/loki/query.go
  pkg/server/server_test.go
  web/locales/en/plugin__network-observability-plugin.json
  web/src/components/filters-toolbar.tsx
Labels: lgtm

#91 NETOBSERV-192 Release action
  .github/workflows/release.yml
Labels: no-qe, lgtm, approved

#78 Prepare FLP integration
  cmd/plugin-backend.go
  pkg/loki/query.go
  pkg/server/server_test.go
  web/locales/en/plugin__network-observability-plugin.json
  web/src/api/ipfix.ts
  web/src/api/loki.ts
  web/src/components/__tests-data__/filters.ts
  web/src/components/__tests-data__/flows.ts
  web/src/components/__tests__/filters-toolbar.spec.tsx
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-tab.tsx
  web/src/components/netflow-table/__tests__/netflow-table-header.spec.tsx
  web/src/utils/columns.ts
Labels: lgtm, approved

#94 NETOBSERV-227 fix filtering by namespace or owner
  pkg/handler/csv/loki_csv.go
  pkg/handler/loki.go
  pkg/handler/response.go
  pkg/loki/query.go
  web/src/utils/columns.ts
Labels: lgtm, approved

#95 Use default TAG=dev to prevent accidental push on main by quay admins
  Makefile
Labels: lgtm, approved

#96 NETOBSERV-223 allow empty values, and some maintenance
  pkg/handler/csv/loki_csv.go
  pkg/handler/loki.go
  pkg/loki/query.go
  web/locales/en/plugin__network-observability-plugin.json
  web/src/components/filter-hints.tsx
  web/src/components/filters-toolbar.tsx
  web/src/utils/label.ts
  web/src/utils/router.ts
Labels: lgtm, approved

#98 NETOBSERV-231 Topology option panel
  web/locales/en/plugin__network-observability-plugin.json
  web/src/components/dropdowns/__tests__/group-dropdown.spec.tsx
  web/src/components/dropdowns/__tests__/layout-dropdown.spec.tsx
  web/src/components/dropdowns/group-dropdown.tsx
  web/src/components/dropdowns/layout-dropdown.tsx
  web/src/components/netflow-topology/__tests__/options-panel.spec.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-topology/options-panel.css
  web/src/components/netflow-topology/options-panel.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/topology.ts
Labels: lgtm
