Repository netobserv/network-observability-console-plugin, pull requests merged in 2022-06, with the labels that each got.

#167 NETOBSERV-316 loki json mocks
  Dockerfile
  Makefile
  cmd/plugin-backend.go
  mocks/loki/flows.json
  mocks/loki/namespaces.json
  mocks/loki/topology.json
  mocks/updateMocks.sh
  pkg/handler/loki.go
  pkg/handler/lokiclientmock/loki_client_mock.go
  pkg/loki/config.go
  pkg/loki/query_test.go
  pkg/server/server_flows_test.go
  web/setup-tests.ts
  web/src/components/__tests-data__/flows.ts
  web/src/components/netflow-table/__tests__/netflow-table.spec.tsx
  web/src/components/netflow-topology/__tests-data__/metrics.ts
  web/src/components/netflow-topology/__tests__/element-panel.spec.tsx
  web/src/components/netflow-topology/__tests__/netflow-topology.spec.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/tsconfig.json
Labels: lgtm

#169 NETOBSERV-317 Netflow table: reduce row height / do not compute in px
  web/src/components/netflow-record/__tests__/record-field.spec.tsx
  web/src/components/netflow-record/record-field.css
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-table/netflow-table.css
  web/src/components/netflow-table/netflow-table.tsx
Labels: lgtm

#164 NETOBSERV-326 data-test attributes
  web/src/components/dropdowns/display-dropdown.tsx
  web/src/components/dropdowns/group-dropdown.tsx
  web/src/components/dropdowns/layout-dropdown.tsx
  web/src/components/dropdowns/metric-function-dropdown.tsx
  web/src/components/dropdowns/metric-type-dropdown.tsx
  web/src/components/dropdowns/query-options-dropdown.tsx
  web/src/components/dropdowns/refresh-dropdown.tsx
  web/src/components/dropdowns/scope-dropdown.tsx
  web/src/components/dropdowns/time-range-dropdown.tsx
  web/src/components/dropdowns/truncate-dropdown.tsx
  web/src/components/filters/autocomplete-filter.tsx
  web/src/components/filters/filter-hints.tsx
  web/src/components/filters/filters-dropdown.tsx
  web/src/components/filters/filters-toolbar.tsx
  web/src/components/modals/columns-modal.tsx
  web/src/components/modals/export-modal.tsx
  web/src/components/modals/modal.tsx
  web/src/components/modals/time-range-modal.tsx
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-table/netflow-table-header.tsx
  web/src/components/netflow-table/netflow-table-row.tsx
  web/src/components/netflow-table/netflow-table.tsx
  web/src/components/netflow-topology/components/edge.tsx
  web/src/components/netflow-topology/element-panel.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-topology/options-panel.tsx
  web/src/components/netflow-traffic-parent.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/summary-panel.tsx
Labels: lgtm, ok-to-test

#174 NETOBSERV-384 Update deprecated console resource tab
  web/console-extensions.json
  web/package-lock.json
  web/package.json
  web/src/components/filters/filters-toolbar.css
  web/src/components/netflow-tab.tsx
  web/src/components/netflow-traffic.css
  web/src/components/netflow-traffic.tsx
Labels: lgtm

#173 NETOBSERV-347 UX filtering: be able to turn off an active filter
  web/src/components/filters/__tests__/filters-toolbar.spec.tsx
  web/src/components/filters/filters-toolbar.css
  web/src/components/filters/filters-toolbar.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/filters.ts
  web/src/utils/local-storage-hook.ts
  web/src/utils/router.ts
Labels: lgtm

#171 NETOBSERV-372 UI: Improve loki error messages
  Makefile
  pkg/handler/flows.go
  pkg/handler/loki.go
  pkg/handler/response.go
  pkg/handler/topology.go
  pkg/server/routes.go
  web/locales/en/plugin__network-observability-plugin.json
  web/setup-tests.ts
  web/src/api/routes.ts
  web/src/components/messages/loki-error.css
  web/src/components/messages/loki-error.tsx
  web/src/components/netflow-table/__tests__/netflow-table.spec.tsx
  web/src/components/netflow-table/netflow-table.tsx
  web/src/components/netflow-topology/__tests__/netflow-topology.spec.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/utils/__tests__/errors.spec.ts
  web/src/utils/errors.ts
Labels: lgtm

#175 NETOBSERV-376 UI: add mac address column / filter
  web/locales/en/plugin__network-observability-plugin.json
  web/src/model/filters.ts
  web/src/utils/columns.ts
  web/src/utils/filter-definitions.ts
Labels: lgtm

#177 NETOBSERV-399 Table rows display issue after update
  web/package-lock.json
  web/package.json
  web/src/components/netflow-table/netflow-table-row.tsx
  web/src/components/netflow-table/netflow-table.tsx
Labels: lgtm

#178 More accurate slowness warnings
  README.md
  web/locales/en/plugin__network-observability-plugin.json
  web/src/components/netflow-traffic.tsx
  web/src/model/filters.ts
Labels: approved
