Repository netobserv/network-observability-console-plugin, pull requests merged in 2022-01, with the labels that each got.

#23 NETOBSERV-72 Filter on any column in NetFlow table
  pkg/handler/loki.go
  pkg/server/server_test.go
  web/.eslintrc.js
  web/i18next-parser.config.js
  web/locales/en/plugin__network-observability-plugin.json
  web/moduleMapper/dummy.ts
  web/package-lock.json
  web/package.json
  web/setup-tests.ts
  web/src/api/routes.ts
  web/src/components/__tests-data__/columns.tsx
  web/src/components/__tests-data__/filters.tsx
  web/src/components/__tests__/columns-modal.spec.tsx
  web/src/components/__tests__/filters-toolbar.spec.tsx
  web/src/components/__tests__/netflow-table-header.spec.tsx
  web/src/components/__tests__/netflow-table-row.spec.tsx
  web/src/components/__tests__/netflow-table.spec.tsx
  web/src/components/__tests__/netflow-traffic.spec.tsx
  web/src/components/__tests__/refresh-dropdown.spec.tsx
  web/src/components/columns-modal.tsx
  web/src/components/filters-toolbar.css
  web/src/components/filters-toolbar.tsx
  web/src/components/netflow-table-header.tsx
  web/src/components/netflow-table-row.tsx
  web/src/components/netflow-table.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/columns.ts
  web/src/utils/duration.tsx
  web/src/utils/router.ts
Labels: no-qe, lgtm

#29 NETOBSERV-117: show loading/empty/error state in netflow table
  web/.eslintrc.js
  web/i18next-parser.config.js
  web/locales/en/plugin__network-observability-plugin.json
  web/moduleMapper/dummy.ts
  web/package-lock.json
  web/package.json
  web/setup-tests.ts
  web/src/components/__tests__/netflow-table.spec.tsx
  web/src/components/filters-toolbar.css
  web/src/components/netflow-table.tsx
  web/src/components/netflow-traffic.tsx
Labels: no-qe, lgtm, approved

#31 Fix Lint Warning
  web/package.json
  web/src/components/filters-toolbar.tsx
  web/src/utils/columns.ts
  web/src/utils/router.ts
Labels: no-qe, lgtm

#32 NETOBSERV-117: show spinning icon when filters are added/deleted
  web/src/components/__tests__/filters-toolbar.spec.tsx
  web/src/components/__tests__/netflow-table.spec.tsx
  web/src/components/filters-toolbar.tsx
  web/src/components/netflow-table.tsx
  web/src/components/netflow-traffic.tsx
Labels: no-qe, lgtm, approved

#35 Dockerfile now use npm ci to prevent lock file modifications
  Dockerfile
  Makefile
Labels: no-qe, lgtm, approved

#33 NETOBSERV-130: vertically aligning spinning icon in refresh button
  web/src/components/netflow-traffic.css
Labels: no-qe, lgtm, approved

#37 Fix sort on refresh
  web/src/components/__tests__/netflow-table.spec.tsx
  web/src/components/netflow-table.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/columns.ts
Labels: lgtm

#34 NETOBSERV-74 moved time filter to dropdown
  pkg/handler/loki.go
  pkg/server/server_test.go
  web/locales/en/plugin__network-observability-plugin.json
  web/src/api/routes.ts
  web/src/components/__tests-data__/filters.tsx
  web/src/components/__tests__/filters-toolbar.spec.tsx
  web/src/components/__tests__/time-range-dropdown.spec.tsx
  web/src/components/__tests__/time-range-modal.spec.tsx
  web/src/components/filters-toolbar.tsx
  web/src/components/netflow-traffic.css
  web/src/components/netflow-traffic.tsx
  web/src/components/time-range-dropdown.tsx
  web/src/components/time-range-modal.css
  web/src/components/time-range-modal.tsx
  web/src/utils/__tests__/datetime.spec.ts
  web/src/utils/columns.ts
  web/src/utils/datetime.ts
  web/src/utils/duration.tsx
  web/src/utils/previous-hook.ts
  web/src/utils/router.ts
Labels: no-qe

#39 NETOBSERV-127: fix a vulnerability and decrease severity of another
  web/package-lock.json
  web/package.json
Labels: no-qe, lgtm, approved

#38 NETOBSERV-84: improve table filter IP address matching
  pkg/handler/loki.go
  pkg/server/server_test.go
  web/locales/en/plugin__network-observability-plugin.json
  web/src/components/__tests__/filters-toolbar.spec.tsx
  web/src/components/filters-toolbar.tsx
  web/src/utils/__tests__/ip.spec.ts
  web/src/utils/ip.ts
Labels: no-qe, lgtm, approved

#40 Few simplifications
  web/package-lock.json
  web/package.json
  web/src/api/loki.ts
  web/src/api/routes.ts
  web/src/components/__tests-data__/columns.tsx
  web/src/components/__tests-data__/flows.tsx
  web/src/components/filters-toolbar.tsx
  web/src/components/netflow-table/__tests__/netflow-table-header.spec.tsx
  web/src/components/netflow-table/__tests__/netflow-table-row.spec.tsx
  web/src/components/netflow-table/__tests__/netflow-table.spec.tsx
  web/src/components/netflow-table/netflow-table-header.tsx
  web/src/components/netflow-table/netflow-table-row.tsx
  web/src/components/netflow-table/netflow-table.tsx
  web/src/components/netflow-traffic.css
  web/src/components/netflow-traffic.tsx
  web/src/components/refresh-dropdown.tsx
  web/src/utils/__tests__/base-compare.spec.ts
  web/src/utils/__tests__/ip.spec.ts
  web/src/utils/__tests__/port.spec.ts
  web/src/utils/__tests__/protocol.spec.ts
  web/src/utils/base-compare.ts
  web/src/utils/columns.ts
  web/src/utils/duration.ts
  web/src/utils/ip.ts
  web/src/utils/port.ts
  web/src/utils/protocol.ts
  web/src/utils/router.ts
Labels: no-qe, lgtm, approved

#41 NETOBSERV-128 filters bugfix
  web/src/components/__tests__/filters-toolbar.spec.tsx
  web/src/components/filters-toolbar.css
  web/src/components/filters-toolbar.tsx
  web/src/components/netflow-traffic.tsx
Labels: no-qe, lgtm

#43 NETOBSERV-132 improved table display
  web/locales/en/plugin__network-observability-plugin.json
  web/src/components/__tests__/display-dropdown.spec.tsx
  web/src/components/columns-modal.tsx
  web/src/components/display-dropdown.tsx
  web/src/components/netflow-table/__tests__/netflow-table-row.spec.tsx
  web/src/components/netflow-table/__tests__/netflow-table.spec.tsx
  web/src/components/netflow-table/netflow-table-header.tsx
  web/src/components/netflow-table/netflow-table-row.css
  web/src/components/netflow-table/netflow-table-row.tsx
  web/src/components/netflow-table/netflow-table.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/columns.ts
Labels: no-qe, lgtm

#46 NETOBSERV-125 localStorage hook
  web/setup-tests.ts
  web/src/components/__tests__/netflow-traffic.spec.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/local-storage-hook.ts
Labels: lgtm

#47 NETOBSERV-120 table row stripping
  web/src/components/netflow-table/netflow-table-row.css
Labels: lgtm

#50 Fix loki filtering server flaky test
  pkg/server/server_test.go
Labels: no-qe, lgtm, approved

#49 Fix flaky test starting servers
  pkg/server/server_test.go
Labels: no-qe, lgtm, approved

#42 NETOBSERV-134 Add some columns
  .golangci.yml
  pkg/handler/loki.go
  web/locales/en/plugin__network-observability-plugin.json
  web/src/api/ipfix.ts
  web/src/api/loki.ts
  web/src/api/routes.ts
  web/src/components/__tests-data__/filters.ts
  web/src/components/__tests-data__/flows.ts
  web/src/components/__tests__/filters-toolbar.spec.tsx
  web/src/components/__tests__/query-options-dropdown.spec.tsx
  web/src/components/filters-toolbar.tsx
  web/src/components/netflow-table/__tests__/netflow-table-row.spec.tsx
  web/src/components/netflow-table/netflow-table-row.tsx
  web/src/components/netflow-table/netflow-table.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-options-dropdown.tsx
  web/src/model/query-options.ts
  web/src/utils/columns.ts
  web/src/utils/filters.ts
  web/src/utils/router.ts
Labels: no-qe, lgtm, approved

#48 NETOBSERV-116: Fix namespace deployment
  web/src/api/routes.ts
Labels: no-qe, lgtm, approved

#53 Fix filters params
  pkg/handler/loki.go
Labels: no-qe, lgtm

#51 Fix displaying some errors (e.g. plain text response)
  web/src/components/netflow-traffic.tsx
  web/src/utils/__tests__/errors.spec.ts
  web/src/utils/errors.ts
Labels: no-qe, lgtm, approved

#44 NETOBSERV-121 tab pages
  web/console-extensions.json
  web/locales/en/plugin__network-observability-plugin.json
  web/package-lock.json
  web/package.json
  web/setup-tests.ts
  web/src/components/__tests-data__/tabs.tsx
  web/src/components/__tests__/filters-toolbar.spec.tsx
  web/src/components/__tests__/netflow-tab.spec.tsx
  web/src/components/filters-toolbar.tsx
  web/src/components/netflow-tab.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/router.ts
Labels: no-qe, lgtm

#55 Fixing the make bridge command
  Makefile
Labels: no-qe, lgtm, approved

#56 Fixed modified plugin proxy url
  Makefile
  web/src/api/routes.ts
Labels: no-qe, lgtm, approved

#54 NETOBSERV-159 fix several issues in LoQL builder
  pkg/handler/loki.go
  pkg/handler/loki_test.go
  pkg/server/server_test.go
  web/src/utils/router.ts
Labels: no-qe, lgtm, approved

#58 NETOBSERV-121 removed deployment tab
  web/console-extensions.json
Labels: lgtm

#57 NETOBSERV-133: Fix logql injection from filters
  pkg/handler/loki.go
  pkg/handler/loki_test.go
  pkg/server/server_test.go
Labels: no-qe, lgtm, approved

#59 NETOBSERV-121 restore deployment tab
  README.md
  web/console-extensions.json
  web/webpack.config.ts
Labels: no-qe, lgtm, approved
