Repository netobserv/network-observability-console-plugin, pull requests merged in 2022-02, with the labels that each got.

#60 Fix Deployment filters, add more tabs...
  web/console-extensions.json
  web/src/components/netflow-tab.tsx
  web/src/utils/columns.ts
  web/src/utils/filters.ts
Labels: no-qe, lgtm, approved

#63 Align table filter controls
  web/src/components/filters-toolbar.tsx
Labels: no-qe, lgtm, approved

#62 NETOBSERV-149 Nested columns src/dest
  web/locales/en/plugin__network-observability-plugin.json
  web/src/components/__tests-data__/columns.ts
  web/src/components/__tests__/columns-modal.spec.tsx
  web/src/components/__tests__/filters-toolbar.spec.tsx
  web/src/components/columns-modal.tsx
  web/src/components/filters-toolbar.css
  web/src/components/filters-toolbar.tsx
  web/src/components/netflow-table/__tests__/netflow-table-header.spec.tsx
  web/src/components/netflow-table/__tests__/netflow-table-row.spec.tsx
  web/src/components/netflow-table/__tests__/netflow-table.spec.tsx
  web/src/components/netflow-table/netflow-table-header.tsx
  web/src/components/netflow-table/netflow-table-row.css
  web/src/utils/columns.ts
Labels: no-qe

#52 Fixed width columns
  web/src/components/netflow-table/__tests__/netflow-table-header.spec.tsx
  web/src/components/netflow-table/netflow-table-header.tsx
  web/src/components/netflow-table/netflow-table.tsx
  web/src/components/netflow-traffic.css
  web/src/utils/columns.ts
Labels: no-qe, approved

#66 NETOBSERV-138 improved filter validation
  web/locales/en/plugin__network-observability-plugin.json
  web/src/components/__tests__/filters-toolbar.spec.tsx
  web/src/components/filters-toolbar.css
  web/src/components/filters-toolbar.tsx
Labels: lgtm

#67 Disabling and sign in flows request
  pkg/handler/loki.go
Labels: no-qe, lgtm, approved

#61 NETOBSERV-115 details view
  Makefile
  web/locales/en/plugin__network-observability-plugin.json
  web/src/api/ipfix.ts
  web/src/api/loki.ts
  web/src/components/__tests-data__/flows.ts
  web/src/components/filters-toolbar.tsx
  web/src/components/netflow-record/__tests__/record-field.spec.tsx
  web/src/components/netflow-record/__tests__/record-panel.spec.tsx
  web/src/components/netflow-record/record-field.css
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-record/record-panel.css
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-table/__tests__/netflow-table-row.spec.tsx
  web/src/components/netflow-table/__tests__/netflow-table.spec.tsx
  web/src/components/netflow-table/netflow-table-header.tsx
  web/src/components/netflow-table/netflow-table-row.css
  web/src/components/netflow-table/netflow-table-row.tsx
  web/src/components/netflow-table/netflow-table.tsx
  web/src/components/netflow-traffic.css
  web/src/components/netflow-traffic.tsx
  web/src/utils/hash.ts
  web/src/utils/router.ts
Labels: no-qe, lgtm

#64 NETOBSERV-73: filter by matching "all" or "any" the criteria
  go.sum
  pkg/handler/loki.go
  pkg/handler/loki_test.go
  pkg/loki/convert.go
  pkg/loki/filter.go
  pkg/loki/query.go
  pkg/loki/query_test.go
  pkg/server/server_test.go
  web/locales/en/plugin__network-observability-plugin.json
  web/src/components/__tests__/filters-toolbar.spec.tsx
  web/src/components/__tests__/query-options-dropdown.spec.tsx
  web/src/components/netflow-record/__tests__/record-panel.spec.tsx
  web/src/components/query-options-dropdown.tsx
  web/src/model/query-options.ts
  web/src/utils/router.ts
Labels: no-qe, lgtm, approved

#70 NETOBSERV-169 labels from flag
  cmd/plugin-backend.go
  pkg/handler/loki.go
  pkg/loki/query.go
  pkg/loki/query_test.go
  pkg/server/server_test.go
  pkg/utils/utils.go
Labels: lgtm

#72 Fix regexp to validate filter when multiple values are combined
  pkg/loki/query.go
Labels: no-qe, lgtm, approved

#77 FlowDirection must be read from labels now
  pkg/loki/query.go
  web/src/api/ipfix.ts
  web/src/components/__tests-data__/flows.ts
  web/src/utils/columns.ts
Labels: no-qe, lgtm, approved

#69 hot reloading + devdependencies
  Makefile
  web/package-lock.json
  web/package.json
  web/tsconfig.json
  web/webpack.config.ts
Labels: no-qe

#76 Add missing types
  web/package-lock.json
  web/package.json
Labels: no-qe

#80 NETOBSERV-187 : Restrict port to service formatting to ports below 1024
  web/src/utils/__tests__/port.spec.ts
  web/src/utils/filters.ts
  web/src/utils/port.ts
Labels: no-qe, lgtm, approved

#82 NETOBSERV-176 Filter on exact match
  pkg/loki/query.go
  pkg/loki/query_test.go
  pkg/server/server_test.go
  web/locales/en/plugin__network-observability-plugin.json
  web/src/components/filters-toolbar.tsx
  web/src/utils/label.ts
Labels: lgtm

#84 NETOBSERV-210 fix console require error
  web/webpack.config.ts
Labels: no-qe, lgtm
