Repository netobserv/network-observability-console-plugin, pull requests merged in 2022-05, with the labels that each got.

#143 NETOBSERV-325 Topology: Remove feature gate
  web/src/components/netflow-traffic.tsx
Labels: no-qe, lgtm, approved

#136 NETOBSERV-287 Aggregate stats, fix limit reach
  pkg/handler/csv/loki_csv.go
  pkg/handler/flows.go
  pkg/handler/loki.go
  pkg/handler/response.go
  pkg/handler/topology.go
  pkg/loki/matrix_merger.go
  pkg/loki/matrix_merger_test.go
  pkg/loki/merger.go
  pkg/loki/streams_merger.go
  pkg/loki/streams_merger_test.go
  pkg/model/loki.go
  pkg/model/loki_test.go
  pkg/server/server_test.go
  web/locales/en/plugin__network-observability-plugin.json
  web/src/api/loki.ts
  web/src/api/routes.ts
  web/src/components/__tests-data__/flows.ts
  web/src/components/__tests__/netflow-traffic.spec.tsx
  web/src/components/dropdowns/__tests__/query-options-dropdown.spec.tsx
  web/src/components/dropdowns/query-options-dropdown.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/__tests__/query-summary.spec.tsx
  web/src/components/query-summary/__tests__/summary-panel.spec.tsx
  web/src/components/query-summary/query-summary.tsx
  web/src/components/query-summary/summary-panel.tsx
Labels: lgtm, approved

#141 NETOBSERV-311 Filtering with autocompletion trigger exact match
  web/src/components/filters/autocomplete-filter.tsx
  web/src/model/filters.ts
  web/src/utils/filter-definitions.ts
Labels: lgtm, approved

#140 NETOBSERV-249 Add more time/duration columns
  web/locales/en/plugin__network-observability-plugin.json
  web/src/api/ipfix.ts
  web/src/api/loki.ts
  web/src/components/__tests-data__/flows.ts
  web/src/components/modals/time-range-modal.tsx
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-table/__tests__/netflow-table-header.spec.tsx
  web/src/components/netflow-table/__tests__/netflow-table.spec.tsx
  web/src/components/netflow-table/netflow-table-header.tsx
  web/src/utils/columns.ts
  web/src/utils/duration.ts
Labels: lgtm, approved

#147 NETOBSERV-219 PoC Operators - skip TLS checks
  cmd/plugin-backend.go
  pkg/handler/loki.go
  pkg/httpclient/http_client.go
  pkg/loki/config.go
  pkg/loki/query_test.go
  pkg/server/server_flows_test.go
Labels: lgtm

#142 NETOBSERV-312 - Full screen mode
  web/locales/en/plugin__network-observability-plugin.json
  web/setup-tests.ts
  web/src/components/dropdowns/__tests__/query-options-dropdown.spec.tsx
  web/src/components/dropdowns/__tests__/truncate-dropdown.spec.tsx
  web/src/components/dropdowns/display-dropdown.tsx
  web/src/components/dropdowns/query-options-dropdown.tsx
  web/src/components/dropdowns/truncate-dropdown.tsx
  web/src/components/filters/__tests__/filters-toolbar.spec.tsx
  web/src/components/filters/filters-toolbar.css
  web/src/components/filters/filters-toolbar.tsx
  web/src/components/netflow-topology/options-panel.css
  web/src/components/netflow-topology/options-panel.tsx
  web/src/components/netflow-traffic.css
  web/src/components/netflow-traffic.tsx
  web/src/model/topology.ts
Labels: lgtm

#149 NETOBSERV-290 Preserve settings in NetFlow table
  web/src/components/modals/export-modal.tsx
  web/src/components/netflow-table/__tests__/netflow-table-header.spec.tsx
  web/src/components/netflow-table/__tests__/netflow-table.spec.tsx
  web/src/components/netflow-table/netflow-table-header.tsx
  web/src/components/netflow-table/netflow-table.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/local-storage-hook.ts
  web/src/utils/url.ts
Labels: lgtm

#144 NETOBSERV-313 Topology: automatically fit view
  web/src/components/netflow-topology/netflow-topology.tsx
Labels: lgtm

#150 NETOBSERV-298 Custom time range forgets the seconds
  web/src/components/modals/__tests__/time-range-modal.spec.tsx
  web/src/components/modals/time-range-modal.tsx
Labels: lgtm

#146 NETOBSERV-253 Topology: Enrich Host informations
  pkg/loki/topology_query.go
  pkg/model/fields/fields.go
  pkg/server/server_test.go
  web/locales/en/plugin__network-observability-plugin.json
  web/src/api/ipfix.ts
  web/src/api/loki.ts
  web/src/components/filters/__tests__/text-filter.spec.tsx
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-topology/element-panel.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/model/filters.ts
  web/src/model/topology.ts
  web/src/utils/columns.ts
  web/src/utils/filter-definitions.ts
Labels: lgtm

#145 NETOBSERV-259 Topology: Filter from side panel
  web/src/components/netflow-topology/__tests__/element-panel.spec.tsx
  web/src/components/netflow-topology/element-panel.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/topology.ts
Labels: lgtm

#153 NETOBSERV-265 millisecond accuracy for time flow start/end
  web/src/api/ipfix.ts
  web/src/components/__tests-data__/flows.ts
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-table/__tests__/netflow-table.spec.tsx
  web/src/utils/columns.ts
  web/src/utils/duration.ts
Labels: lgtm, approved

#154 NETOBSERV-290 fix tick race issues
  web/src/components/__tests__/netflow-traffic.spec.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/poll-hook.ts
Labels: lgtm, ok-to-test

#157 NETOBSERV-344 Can't click on node info from popup
  web/src/components/netflow-topology/components/node.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-topology/styles/styleNode.tsx
  web/src/model/topology.ts
Labels: lgtm, ok-to-test

#158 NETOBSERV-361 Fix time range url issue
  web/src/utils/router.ts
Labels: lgtm

#160 NETOBSERV-363 Bidirectional edges doesn't work anymore
  web/src/components/netflow-topology/element-panel.tsx
  web/src/model/topology.ts
Labels: lgtm, ok-to-test

#162 NETOBSERV-292 End time for time range is now inclusive
  pkg/handler/flows.go
  pkg/handler/topology.go
  pkg/server/server_flows_test.go
  web/locales/en/plugin__network-observability-plugin.json
  web/src/components/modals/time-range-modal.tsx
  web/src/components/netflow-record/record-panel.tsx
Labels: lgtm, approved

#155 Cypress integration tests
  .gitignore
  Makefile
  web/cypress.json
  web/cypress/integration/table/table.spec.js
  web/cypress/integration/topology/topology.spec.js
  web/cypress/plugins/index.js
  web/cypress/support/commands.js
  web/cypress/support/const.js
  web/cypress/support/index.js
  web/package-lock.json
  web/package.json
Labels: lgtm

#161 NETOBSERV-364 Topology crash on scope change with groups
  web/src/components/netflow-topology/netflow-topology.tsx
Labels: lgtm, ok-to-test

#165 NETOBSERV-377 Filtering in topology triggers exact match
  web/src/model/topology.ts
Labels: lgtm, approved
