Repository netobserv/network-observability-console-plugin, pull requests merged in 2023-06, with the labels that each got.

#335 Add metrics to overview div
  web/src/components/metrics/metrics-content.tsx
  web/src/components/metrics/stat-donut.tsx
Labels: lgtm, approved

#317 NETOBSERV-915 add conversation direction
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/dropdowns/query-options-dropdown.tsx
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/columns.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#338 Add length to metrics
  web/src/components/metrics/metrics-content.tsx
  web/src/components/metrics/stat-donut.tsx
Labels: lgtm, approved

#342 Fix missing results in merged streams
  pkg/loki/streams_merger.go
  pkg/loki/streams_merger_test.go
  pkg/model/loki.go
  pkg/model/loki_test.go
Labels: no-qe, lgtm, approved, no-doc

#341 NETOBSERV-1090: initialize empty slice for returning json [1.3 backport]
  pkg/utils/utils.go
Labels: lgtm, approved, qe-approved, ok-to-test, jira/valid-reference

#349 NETOBSERV-997 Cypress test console errors
  web/src/components/netflow-traffic.tsx
Labels: lgtm, approved, qe-approved, ok-to-test
