Repository netobserv/network-observability-console-plugin, pull requests merged in 2023-05, with the labels that each got.

#315 NETOBSERV-765 Restore metrics
  cmd/plugin-backend.go
  pkg/server/metrics_server.go
  pkg/server/routes.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: approved, qe-approved, ok-to-test

#300 NETOBSERV-901 Declare Observe section for project admins
  web/console-extensions.json
  web/locales/en/plugin__netobserv-plugin.json
  web/src/i18n.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#298 NETOBSERV-849 Console plugin multi-arch builds (upstream)
  .github/workflows/pull_request.yml
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  .mk/shortcuts.mk
  Dockerfile
  Makefile
  README.md
Labels: lgtm, approved

#327 fix makefile
  .github/workflows/push_image_pr.yml
  Makefile
Labels: lgtm, approved

#330 fix manifest build target
  Makefile
Labels: lgtm, approved, ok-to-test

#326 NETOBSERV-972 check if cluster admin via namespaces
  cmd/plugin-backend.go
  pkg/kubernetes/auth/check_auth.go
  pkg/kubernetes/auth/check_auth_test.go
  pkg/kubernetes/client/client.go
Labels: approved, ok-to-test

#331 Update workflow, setup workflow-test
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  .mk/shortcuts.mk
  Makefile
  shortlived.Dockerfile
Labels: lgtm, approved

#322 NETOBSERV-669: overview export PNG
  Makefile
  web/locales/en/plugin__netobserv-plugin.json
  web/package-lock.json
  web/package.json
  web/src/components/netflow-overview/netflow-overview-panel.tsx
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-overview/panel-kebab.tsx
  web/src/components/netflow-topology/2d/topology-content.tsx
  web/src/components/netflow-traffic.tsx
  web/src/typedefs/save-svg-as-png.d.ts
  web/src/utils/export.ts
Labels: lgtm, approved, qe-approved, jira/valid-reference
