Repository netobserv/network-observability-console-plugin, pull requests merged in 2023-10, with the labels that each got.

#402 NETOBSERV-1313 enable feature gated panels by default
  web/src/utils/overview-panels.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#389 NETOBSERV-1185 Console plugin async overview metrics
  mocks/loki/flow_metrics_app.json
  mocks/loki/flow_metrics_dropped_app.json
  mocks/loki/flow_metrics_dropped_cause.json
  mocks/loki/flow_metrics_dropped_host.json
  mocks/loki/flow_metrics_dropped_namespace.json
  mocks/loki/flow_metrics_dropped_owner.json
  mocks/loki/flow_metrics_dropped_resource.json
  mocks/loki/flow_metrics_dropped_state.json
  mocks/loki/flow_metrics_host.json
  mocks/loki/flow_metrics_namespace.json
  mocks/loki/flow_metrics_owner.json
  mocks/loki/flow_metrics_resource.json
  mocks/loki/flow_records.json
  mocks/loki/flow_records_dropped.json
  mocks/loki/flow_records_has_dropped.json
  mocks/loki/flow_records_sent.json
  mocks/updateMocks.sh
  pkg/handler/lokiclientmock/loki_client_mock.go
  pkg/server/routes.go
  pkg/server/server_flows_test.go
  pkg/server/server_test.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/loki.ts
  web/src/api/routes.ts
  web/src/components/__tests-data__/config.ts
  web/src/components/__tests-data__/flows.ts
  web/src/components/__tests__/netflow-tab.spec.tsx
  web/src/components/__tests__/netflow-traffic.spec.tsx
  web/src/components/messages/loki-error.tsx
  web/src/components/metrics/dropped-donut.tsx
  web/src/components/metrics/latency-donut.tsx
  web/src/components/metrics/metrics-content.tsx
  web/src/components/metrics/metrics-total-content.tsx
  web/src/components/metrics/single-metrics-total-content.tsx
  web/src/components/metrics/stat-donut.tsx
  web/src/components/netflow-overview/__tests__/netflow-overview.spec.tsx
  web/src/components/netflow-overview/netflow-overview-panel.css
  web/src/components/netflow-overview/netflow-overview.css
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/__tests__/metrics-query-summary.spec.tsx
  web/src/components/query-summary/flows-query-summary.tsx
  web/src/components/query-summary/metrics-query-summary.tsx
  web/src/components/query-summary/query-summary.css
  web/src/components/query-summary/stats-query-summary.tsx
  web/src/components/query-summary/summary-panel.tsx
  web/src/utils/__tests__/back-and-forth.spec.ts
  web/src/utils/back-and-forth.ts
  web/src/utils/local-storage-hook.ts
  web/src/utils/overview-panels.ts
Labels: lgtm, approved, qe-approved, ok-to-test, testing-breaking-change

#401 NETOBSERV-1337 DSCP filter & side panel details
  pkg/model/fields/fields.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/ipfix.ts
  web/src/components/netflow-record/record-field.tsx
  web/src/model/filters.ts
  web/src/utils/dscp.ts
  web/src/utils/filter-definitions.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#408 NETOBSERV-1274 add missing labels to defaults
  cmd/plugin-backend.go
Labels: no-qe, lgtm, approved, no-doc

#404 NETOBSERV-1288 RTT feedback
  web/docs/interfaces/Fields.md
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/ipfix.ts
  web/src/utils/columns.ts
  web/src/utils/filter-definitions.ts
  web/src/utils/overview-panels.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#414 NETOBSERV-1288 enable rtt column by default
  web/src/utils/columns.ts
Labels: lgtm, approved, ok-to-test

#415 Workflow: build images from release branches
  .github/workflows/push_image.yml
Labels: lgtm, approved
