Repository netobserv/network-observability-console-plugin, pull requests merged in 2023-11, with the labels that each got.

#422 NETOBSERV-1316 & NETOBSERV-1380 - Get dns noError codes to always show graphs
  pkg/loki/flow_query.go
  web/src/components/metrics/latency-donut.tsx
  web/src/components/metrics/single-metrics-total-content.tsx
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/metrics-query-summary.tsx
  web/src/utils/columns.ts
  web/src/utils/metrics.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#423 NETOBSERV-1353 Console plugin feedback
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/__tests-data__/flows.ts
  web/src/components/netflow-record/__tests__/record-panel.spec.tsx
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-record/record-panel.tsx
  web/src/model/filters.ts
  web/src/utils/columns.ts
  web/src/utils/dscp.ts
  web/src/utils/filter-definitions.ts
  web/src/utils/filter-options.ts
  web/src/utils/icmp.ts
  web/src/utils/protocol.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#425 NETOBSERV-1379: show DNS error number
  pkg/loki/flow_query.go
  pkg/loki/topology_query.go
  pkg/model/fields/fields.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/ipfix.ts
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/filters.ts
  web/src/utils/columns.ts
  web/src/utils/dns.ts
  web/src/utils/filter-definitions.ts
  web/src/utils/filter-options.ts
Labels: lgtm, approved, qe-approved, jira/valid-reference

#427 NETOBSERV-1400 Feature filters are observed even though they are not enabled
  Makefile
  config/sample-config.yaml
  mocks/loki/flow_records.json
  web/src/api/ipfix.ts
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/columns.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#429 NETOBSERV-1402 Add extra data-test attributes for cypress
  web/src/components/netflow-table/netflow-table-row.tsx
  web/src/components/netflow-table/netflow-table.tsx
Labels: no-qe, lgtm, approved

#405 NETOBSERV-1319 single graph focus
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/dropdowns/overview-display-dropdown.css
  web/src/components/dropdowns/overview-display-dropdown.tsx
  web/src/components/metrics/__tests__/metrics-content.spec.tsx
  web/src/components/metrics/dropped-donut.tsx
  web/src/components/metrics/histogram.tsx
  web/src/components/metrics/latency-donut.tsx
  web/src/components/metrics/metrics-content.tsx
  web/src/components/metrics/metrics-helper.tsx
  web/src/components/metrics/metrics-total-content.tsx
  web/src/components/metrics/single-metrics-total-content.tsx
  web/src/components/metrics/stat-donut.tsx
  web/src/components/netflow-overview/__tests__/netflow-overview-panel.spec.tsx
  web/src/components/netflow-overview/netflow-overview-panel.css
  web/src/components/netflow-overview/netflow-overview-panel.tsx
  web/src/components/netflow-overview/netflow-overview.css
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-table/netflow-table.tsx
  web/src/components/netflow-topology/element-panel-metrics.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/local-storage-hook.ts
  web/src/utils/panel.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#428 NETOBSERV-1102: fine-tune http servers
  pkg/server/common.go
  pkg/server/metrics_server.go
  pkg/server/server.go
  pkg/server/server_test.go
Labels: no-qe, lgtm, approved, no-doc, jira/valid-reference

#436 Bump dependencies
  go.mod
  go.sum
  vendor/github.com/gorilla/mux/.editorconfig
  vendor/github.com/gorilla/mux/.gitignore
  vendor/github.com/gorilla/mux/AUTHORS
  vendor/github.com/gorilla/mux/LICENSE
  vendor/github.com/gorilla/mux/Makefile
  vendor/github.com/gorilla/mux/README.md
  vendor/github.com/gorilla/mux/doc.go
  vendor/github.com/gorilla/mux/mux.go
  vendor/github.com/gorilla/mux/regexp.go
  vendor/github.com/gorilla/mux/route.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/LICENSE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/.gitignore
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/Makefile
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/decode.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/doc.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/encode.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/golang.org/x/oauth2/internal/token.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/token.go
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/modules.txt
  web/package-lock.json
  web/package.json
Labels: lgtm, approved
