Repository netobserv/network-observability-console-plugin, pull requests merged in 2023-04, with the labels that each got.

#319 remove tab trailing semicolon
  web/src/components/netflow-tab.tsx
  web/src/components/netflow-traffic.css
Labels: no-qe, lgtm, approved, no-doc

#301 NETOBSERV-922 - Flaky topology data
  web/src/model/topology.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#320 NETOBSERV-972 Make DISABLED auth mode not restricted to admins
  cmd/plugin-backend.go
Labels: lgtm, approved

#323 Update connection tracking tooltip after change in CRD
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/dropdowns/query-options-dropdown.tsx
Labels: lgtm, approved
