Repository netobserv/network-observability-console-plugin, pull requests merged in 2023-02, with the labels that each got.

#272 NETOBSERV-789 UI: Table Histogram shortcuts
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/dropdowns/__tests__/query-options-dropdown.spec.tsx
  web/src/components/dropdowns/query-options-dropdown.tsx
  web/src/components/dropdowns/time-range-dropdown.tsx
  web/src/components/metrics/histogram.css
  web/src/components/metrics/histogram.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/datetime.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#286 Added alert banner in netobserv page
  config/sample-frontend-config.yaml
  pkg/handler/frontend-config.go
  web/locales/en/plugin__netobserv-plugin.json
  web/package-lock.json
  web/package.json
  web/src/api/alert.ts
  web/src/api/routes.ts
  web/src/components/__tests__/netflow-traffic.spec.tsx
  web/src/components/alerts/banner.css
  web/src/components/alerts/banner.tsx
  web/src/components/alerts/fetcher.tsx
  web/src/components/netflow-traffic-parent.tsx
  web/src/model/config.ts
Labels: lgtm, approved

#289 [1.1 backport] NETOBSERV-876 - api subrouter
  pkg/server/routes.go
  pkg/server/server_test.go
Labels: lgtm, approved

#287 NETOBSERV-876 - api subrouter
  pkg/server/routes.go
  pkg/server/server_test.go
Labels: lgtm, approved, ok-to-test

#292 Move to go1.19
  .github/workflows/pull_request.yml
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  .golangci.yml
  Dockerfile
  go.mod
  pkg/handler/frontend-config.go
  pkg/handler/lokiclientmock/loki_client_mock.go
  pkg/httpclient/http_client.go
  pkg/loki/config.go
  pkg/loki/matrix_merger.go
  pkg/model/loki.go
  pkg/server/server_flows_test.go
  pkg/server/server_test.go
Labels: no-qe, lgtm, approved, no-doc

#293 NETOBSERV-794 Quick filters doesn't work in tabs
  web/src/components/filters/filters-toolbar.tsx
Labels: no-qe, lgtm, approved

#282 NETOBSERV-751 UI: Missing unit of measuring for packets in Overview
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/metrics/histogram.tsx
  web/src/components/metrics/metrics-content.tsx
  web/src/components/metrics/metrics-helper.tsx
  web/src/components/metrics/metrics-total-content.tsx
  web/src/components/metrics/stat-donut.tsx
  web/src/components/netflow-topology/element-panel-stats.tsx
  web/src/components/query-summary/__tests__/flows-query-summary.spec.tsx
  web/src/components/query-summary/flows-query-summary.tsx
  web/src/components/query-summary/metrics-query-summary.tsx
  web/src/model/topology.ts
  web/src/utils/__tests__/metrics.spec.ts
  web/src/utils/format.ts
  web/src/utils/metrics.ts
Labels: lgtm, approved

#294 NETOBSERV-903 banner style fix
  web/src/components/alerts/banner.css
  web/src/components/alerts/fetcher.tsx
Labels: no-qe, lgtm, approved, no-doc
