Repository netobserv/network-observability-console-plugin, pull requests merged in 2023-08, with the labels that each got.

#364 Bump libs
  web/package-lock.json
Labels: lgtm, approved

#311 NETOBSERV-1099: remove reporter option
  pkg/handler/flows.go
  pkg/handler/loki.go
  pkg/handler/topology.go
  pkg/handler/validation.go
  pkg/handler/validation_test.go
  pkg/loki/filter.go
  pkg/loki/flow_query.go
  pkg/loki/topology_query.go
  pkg/model/fields/fields.go
  pkg/model/filters/filters.go
  pkg/model/filters/filters_test.go
  pkg/server/server_flows_test.go
  pkg/server/server_test.go
  pkg/utils/constants/constants.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/loki.ts
  web/src/api/routes.ts
  web/src/components/__tests-data__/metrics.ts
  web/src/components/__tests__/netflow-traffic.spec.tsx
  web/src/components/dropdowns/__tests__/query-options-dropdown.spec.tsx
  web/src/components/dropdowns/query-options-dropdown.tsx
  web/src/components/filters/__tests__/filters-toolbar.spec.tsx
  web/src/components/metrics/dropped-donut.tsx
  web/src/components/metrics/histogram.tsx
  web/src/components/metrics/latency-donut.tsx
  web/src/components/metrics/metrics-helper.tsx
  web/src/components/metrics/single-metrics-total-content.tsx
  web/src/components/modals/__tests__/export-modal.spec.tsx
  web/src/components/modals/export-modal.tsx
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-record/__tests__/record-panel.spec.tsx
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-topology/2d/topology-content.tsx
  web/src/components/netflow-topology/3d/three-d-topology-content.tsx
  web/src/components/netflow-topology/__tests-data__/metrics.ts
  web/src/components/netflow-topology/__tests__/element-panel.spec.tsx
  web/src/components/netflow-topology/__tests__/netflow-topology.spec.tsx
  web/src/components/netflow-topology/element-panel-metrics.tsx
  web/src/components/netflow-topology/element-panel-stats.tsx
  web/src/components/netflow-topology/element-panel.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/__tests__/metrics-query-summary.spec.tsx
  web/src/components/query-summary/metrics-query-summary.tsx
  web/src/components/query-summary/summary-panel.tsx
  web/src/model/__tests__/export-query.spec.ts
  web/src/model/flow-query.ts
  web/src/model/topology.ts
  web/src/utils/__tests__/flows.spec.ts
  web/src/utils/__tests__/metrics.spec.ts
  web/src/utils/flows.ts
  web/src/utils/metrics.ts
  web/src/utils/router.ts
  web/src/utils/url.ts
Labels: jira/valid-reference

#362 NETOBSERV-1216 PacketDrop enhancements
  pkg/loki/filter.go
  pkg/loki/flow_query.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/ipfix.ts
  web/src/components/filters/filter-hints.tsx
  web/src/components/filters/filters-dropdown.tsx
  web/src/components/filters/filters-helper.ts
  web/src/components/filters/filters-toolbar.tsx
  web/src/components/netflow-overview/netflow-overview.css
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-overview/panel-kebab.tsx
  web/src/components/netflow-record/record-field.css
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/flows-query-summary.tsx
  web/src/model/filters.ts
  web/src/utils/columns.ts
  web/src/utils/dns.ts
  web/src/utils/filter-definitions.ts
  web/src/utils/filter-options.ts
  web/src/utils/icmp.ts
  web/src/utils/pkt-drop.ts
  web/src/utils/values.ts
Labels: lgtm, approved, ok-to-test

#367 NETOBSERV-1216 pktDrop cause filter
  web/src/components/netflow-record/__tests__/record-panel.spec.tsx
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/filters.ts
  web/src/utils/columns.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#368 NETOBSERV-970 Typo in Query Summary panel
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/__tests-data__/flows.ts
  web/src/components/query-summary/__tests__/flows-query-summary.spec.tsx
  web/src/components/query-summary/flows-query-summary.tsx
  web/src/utils/format.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#370 NETOBSERV-1135: add ovs subsystem drop causes
  web/src/components/netflow-record/record-field.tsx
  web/src/utils/pkt-drop.ts
Labels: lgtm, approved, jira/valid-reference

#369 NETOBSERV-1241 Back and forth show the opposite
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/filters/filters-chips.tsx
Labels: lgtm, approved

#366 NETOBSERV-1235 Reporter option issues
  pkg/handler/flows.go
  pkg/model/filters/filters.go
  pkg/model/filters/filters_test.go
  pkg/server/server_test.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/dropdowns/query-options-dropdown.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/filters.ts
  web/src/model/topology.ts
  web/src/utils/__tests__/flows.spec.ts
  web/src/utils/columns.ts
  web/src/utils/filter-definitions.ts
  web/src/utils/filter-options.ts
  web/src/utils/flows.ts
  web/src/utils/ids.ts
Labels: lgtm, approved, ok-to-test

#373 NETOBSERV-1265 Overview / Topology fully drop metrics doesn't show
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
Labels: lgtm, approved, ok-to-test

#374 NETOBSERV-1235 NETOBSERV-1241 UI Polishing
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/dropdowns/query-options-dropdown.tsx
  web/src/components/filters/filters-chips.tsx
  web/src/components/filters/filters-helper.ts
  web/src/components/overflow/links-overflow.tsx
Labels: lgtm, approved, qe-approved
