Repository netobserv/network-observability-console-plugin, pull requests merged in 2023-03, with the labels that each got.

#283 NETOBSERV-870 implement TokenReview
  Makefile
  cmd/plugin-backend.go
  go.mod
  pkg/handler/auth/check_auth.go
  pkg/handler/loki.go
  pkg/handler/resources.go
  pkg/kubernetes/auth/check_auth.go
  pkg/kubernetes/auth/check_auth_test.go
  pkg/kubernetes/client/client.go
  pkg/server/routes.go
  pkg/server/server.go
  pkg/server/server_test.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: approved, qe-approved, ok-to-test

#296 NETOBSERV-906 Document json format
  Makefile
  web/docs/README.md
  web/docs/enums/FlowDirection.md
  web/docs/interfaces/Fields.md
  web/docs/interfaces/Labels.md
  web/docs/interfaces/Record.md
  web/package-lock.json
  web/package.json
  web/src/api/ipfix.ts
Labels: no-qe, lgtm, approved

#291 Added sampling information in frontend config
  config/sample-frontend-config.yaml
  pkg/handler/frontend-config.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/routes.ts
  web/src/components/query-summary/summary-panel.css
  web/src/components/query-summary/summary-panel.tsx
  web/src/model/config.ts
Labels: lgtm

#285 NETOBSERV-871 UI: Connection tracking query option
  config/sample-frontend-config.yaml
  pkg/handler/flows.go
  pkg/handler/frontend-config.go
  pkg/handler/resources_test.go
  pkg/handler/topology.go
  pkg/loki/flow_query.go
  pkg/loki/query_test.go
  pkg/loki/topology_query.go
  pkg/utils/constants/constants.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/ipfix.ts
  web/src/api/routes.ts
  web/src/components/__tests-data__/config.ts
  web/src/components/__tests-data__/flows.ts
  web/src/components/dropdowns/__tests__/query-options-dropdown.spec.tsx
  web/src/components/dropdowns/query-options-dropdown.tsx
  web/src/components/filters/__tests__/filters-toolbar.spec.tsx
  web/src/components/filters/filters-dropdown.tsx
  web/src/components/filters/filters-helper.ts
  web/src/components/filters/filters-toolbar.tsx
  web/src/components/modals/__tests__/export-modal.spec.tsx
  web/src/components/modals/__tests__/overview-panels-modal.spec.tsx
  web/src/components/modals/overview-panels-modal.tsx
  web/src/components/netflow-overview/__tests__/netflow-overview.spec.tsx
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-record/__tests__/record-field.spec.tsx
  web/src/components/netflow-record/__tests__/record-panel.spec.tsx
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/__tests__/flows-query-summary.spec.tsx
  web/src/components/query-summary/__tests__/summary-panel.spec.tsx
  web/src/components/query-summary/flows-query-summary.tsx
  web/src/components/query-summary/summary-panel.tsx
  web/src/model/__tests__/export-query.spec.ts
  web/src/model/config.ts
  web/src/model/filters.ts
  web/src/model/flow-query.ts
  web/src/utils/columns.ts
  web/src/utils/filter-definitions.ts
  web/src/utils/overview-panels.ts
  web/src/utils/router.ts
  web/src/utils/url.ts
Labels: lgtm, approved, qe-approved, breaking-change

#295 NETOBSERV-867 UI: Table Histogram help
  web/assets/histogram-pages.gif
  web/assets/histogram-zoom.gif
  web/assets/histogram.gif
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/guided-tour/guided-tour.css
  web/src/components/guided-tour/guided-tour.tsx
  web/src/components/metrics/histogram.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/local-storage-hook.ts
  web/webpack.config.ts
  web/webpack.standalone.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#284 NETOBSERV-779 topology view crashes when layout display changed to Grid
  web/cypress.config.ts
  web/cypress.json
  web/cypress/e2e/overview/overview.spec.ts
  web/cypress/e2e/table/table.spec.ts
  web/cypress/e2e/topology/topology.spec.ts
  web/cypress/support/commands.js
  web/cypress/support/commands.ts
  web/cypress/support/const.ts
  web/cypress/support/e2e.ts
  web/package-lock.json
  web/package.json
  web/src/components/dropdowns/overview-display-dropdown.tsx
  web/src/components/dropdowns/table-display-dropdown.tsx
  web/src/components/dropdowns/topology-display-dropdown.tsx
  web/src/components/modals/__tests__/time-range-modal.spec.tsx
  web/src/components/modals/time-range-modal.tsx
  web/src/components/netflow-traffic.tsx
Labels: lgtm, approved, qe-approved, ok-to-test

#303 NETOBSERV-916 Higher CPU utilization seen due to connection tracking
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/dropdowns/__tests__/query-options-dropdown.spec.tsx
  web/src/components/dropdowns/query-options-dropdown.tsx
  web/src/components/filters/__tests__/filters-toolbar.spec.tsx
  web/src/components/netflow-traffic.tsx
Labels: lgtm, approved, qe-approved, ok-to-test

#304 NETOBSERV-919 Histogram user experience feedback
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/guided-tour/guided-tour.tsx
  web/src/components/metrics/histogram.tsx
  web/src/components/metrics/metrics-content.css
  web/src/components/netflow-traffic.css
  web/src/components/netflow-traffic.tsx
  web/src/utils/highlight-hook.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#308 Check i18n on PR check
  Makefile
Labels: no-qe, lgtm, approved, no-doc

#309 Bump glob-parent through overrides
  web/package-lock.json
  web/package.json
Labels: no-qe, lgtm, approved, no-doc

#305 NETOBSERV-678 Health dashboard link
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/alerts/banner.tsx
  web/src/components/alerts/fetcher.tsx
  web/src/components/messages/loki-error.tsx
Labels: lgtm, approved

#306 Nit CSS updates
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/metrics/histogram.css
  web/src/components/metrics/histogram.tsx
  web/src/components/netflow-table/netflow-table-header.tsx
  web/src/components/netflow-traffic.css
Labels: no-qe, lgtm, approved, no-doc

#310 NETOBSERV-857 After some time, it fails to retrieve flows
  pkg/handler/loki.go
  pkg/loki/config.go
  pkg/server/server_test.go
Labels: lgtm, approved, qe-approved, ok-to-test

#313 NETOBSERV-908: Added query to get silenced alert and only display non silenced alert
  web/src/api/alert.ts
  web/src/api/routes.ts
  web/src/components/__tests__/netflow-traffic.spec.tsx
  web/src/components/alerts/fetcher.tsx
Labels: lgtm, approved, qe-approved, jira/valid-reference

#316 NETOBSERV-908: (backport) Added query to get silenced alert
  web/src/api/alert.ts
  web/src/api/routes.ts
  web/src/components/__tests__/netflow-traffic.spec.tsx
  web/src/components/alerts/fetcher.tsx
Labels: lgtm, approved, qe-approved, jira/valid-reference

#314 [Backport] NETOBSERV-844 Unable to have a working statusUrl in FlowCollector with Loki Operator 5.6
  cmd/plugin-backend.go
  pkg/handler/export.go
  pkg/handler/flows.go
  pkg/handler/loki.go
  pkg/handler/resources.go
  pkg/handler/topology.go
  pkg/httpclient/http_client.go
  pkg/loki/config.go
  pkg/loki/query_test.go
  pkg/server/server_flows_test.go
Labels: lgtm, approved

#312 NETOBSERV-844 Unable to have a working statusUrl in FlowCollector with Loki Operator 5.6
  cmd/plugin-backend.go
  pkg/handler/export.go
  pkg/handler/flows.go
  pkg/handler/loki.go
  pkg/handler/resources.go
  pkg/handler/topology.go
  pkg/httpclient/http_client.go
  pkg/loki/config.go
  pkg/loki/query_test.go
  pkg/server/server_flows_test.go
Labels: lgtm, approved, qe-approved, ok-to-test
