Repository netobserv/network-observability-console-plugin, pull requests merged in 2023-07, with the labels that each got.

#351 Allow faster frontend builds
  Dockerfile
  Makefile
  README.md
  web/package.json
Labels: lgtm, approved

#353 github ok-to-test: add more info in comment
  .github/workflows/push_image_pr.yml
Labels: lgtm, approved

#354 Upgrade linter - fix found issues - use go1.20
  .github/workflows/pull_request.yml
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  .golangci.yml
  Dockerfile
  Makefile
  go.mod
  pkg/handler/csv/loki_csv.go
  pkg/handler/status.go
  pkg/kubernetes/auth/check_auth.go
  pkg/server/server_test.go
Labels: lgtm, approved

#350 NETOBSERV-1097 react-router-dom upgrade with dynamic loader
  web/package-lock.json
  web/package.json
  web/setup-tests.tsx
  web/src/api/ipfix.ts
  web/src/app.tsx
  web/src/components/alerts/banner.tsx
  web/src/components/dynamic-loader/dynamic-loader.tsx
  web/src/components/filters/filters-toolbar.tsx
  web/src/components/messages/loki-error.tsx
  web/src/components/netflow-overview/panel-kebab.tsx
  web/src/components/netflow-traffic-parent.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/router.ts
  web/src/utils/url.ts
Labels: lgtm, approved

#357 NETOBSERV-1197: Generalize TCPDrop to include more protocols
  config/sample-frontend-config.yaml
  mocks/loki/flows.json
  mocks/loki/flows_dropped.json
  mocks/loki/flows_has_dropped.json
  mocks/loki/flows_sent.json
  mocks/loki/namespaces.json
  mocks/loki/topology_app.json
  mocks/loki/topology_dropped_app.json
  mocks/loki/topology_dropped_cause.json
  mocks/loki/topology_dropped_host.json
  mocks/loki/topology_dropped_namespace.json
  mocks/loki/topology_dropped_owner.json
  mocks/loki/topology_dropped_resource.json
  mocks/loki/topology_dropped_state.json
  mocks/loki/topology_host.json
  mocks/loki/topology_namespace.json
  mocks/loki/topology_owner.json
  mocks/loki/topology_resource.json
  mocks/updateMocks.sh
  pkg/handler/lokiclientmock/loki_client_mock.go
  pkg/loki/flow_query.go
  pkg/loki/topology_query.go
  pkg/model/fields/fields.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/ipfix.ts
  web/src/api/loki.ts
  web/src/components/__tests-data__/config.ts
  web/src/components/dropdowns/__tests__/query-options-dropdown.spec.tsx
  web/src/components/dropdowns/query-options-dropdown.tsx
  web/src/components/filters/__tests__/filters-toolbar.spec.tsx
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/config.ts
  web/src/utils/columns.ts
  web/src/utils/metrics.ts
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#343 NETOBSERV-1025: include back and forth traffic
  Dockerfile
  web/.eslintrc.js
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/filters/__tests__/filters-chips.spec.tsx
  web/src/components/filters/__tests__/filters-toolbar.spec.tsx
  web/src/components/filters/filter-action-links.tsx
  web/src/components/filters/filters-chips.tsx
  web/src/components/filters/filters-helper.ts
  web/src/components/filters/filters-toolbar.css
  web/src/components/filters/filters-toolbar.tsx
  web/src/components/filters/summary-filter-button.tsx
  web/src/components/netflow-tab.tsx
  web/src/components/netflow-topology/2d/components/edge.tsx
  web/src/components/netflow-topology/2d/styles/styleDecorator.tsx
  web/src/components/netflow-topology/2d/styles/styleDecorators.tsx
  web/src/components/netflow-topology/2d/styles/styleNode.tsx
  web/src/components/netflow-topology/2d/topology-content.tsx
  web/src/components/netflow-topology/__tests__/element-panel.spec.tsx
  web/src/components/netflow-topology/__tests__/netflow-topology.spec.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-traffic.css
  web/src/components/netflow-traffic.tsx
  web/src/components/overflow/links-overflow.tsx
  web/src/components/tooltip/maybe-tooltip.tsx
  web/src/model/__tests__/flow-query.spec.ts
  web/src/model/filters.ts
  web/src/model/flow-query.ts
  web/src/model/topology.ts
  web/src/utils/__tests__/filter-definitions.spec.ts
  web/src/utils/__tests__/port.spec.ts
  web/src/utils/__tests__/router.spec.ts
  web/src/utils/filter-definitions.ts
  web/src/utils/router.ts
  web/src/utils/url.ts
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#358 Mention 'dropped by the kernel'
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/ipfix.ts
  web/src/components/dropdowns/query-options-dropdown.tsx
  web/src/utils/overview-panels.ts
Labels: no-qe, lgtm, approved, no-doc

#360 NETOBSERV-1200: Show "< 1ms" for 0 latency instead of n/a
  web/src/components/__tests-data__/flows.ts
  web/src/components/netflow-record/__tests__/record-field.spec.tsx
  web/src/utils/columns.ts
Labels: lgtm, approved, qe-approved, ok-to-test, jira/valid-reference

#344 NETOBSERV-1098: Show scope as slider
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/scope-slider/scope-slider.css
  web/src/components/scope-slider/scope-slider.tsx
  web/src/components/slider/Slider.tsx
  web/src/components/slider/SliderStep.tsx
Labels: approved, qe-approved, ok-to-test, jira/valid-reference

#363 Fix filters comparison
  web/src/components/filters/filters-chips.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/overflow/links-overflow.tsx
  web/src/model/__tests__/filters.spec.ts
  web/src/model/filters.ts
  web/src/model/flow-query.ts
  web/src/utils/base-compare.ts
Labels: lgtm, approved, qe-approved
