Repository netobserv/network-observability-console-plugin, pull requests merged in 2023-09, with the labels that each got.

#376 NETOBSERV-1242 Console plugin build infos
  cmd/plugin-backend.go
  pkg/handler/frontend-config.go
  pkg/server/routes.go
  pkg/server/server.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/routes.ts
  web/src/components/query-summary/summary-panel.tsx
  web/src/model/config.ts
Labels: lgtm, approved, qe-approved

#377 NETOBSERV-1266 Netflow traffic tab crash
  web/src/app.tsx
  web/src/components/__tests__/netflow-tab.spec.tsx
  web/src/components/dynamic-loader/dynamic-loader.tsx
  web/src/components/netflow-tab.tsx
  web/src/components/netflow-traffic.tsx
  web/webpack.standalone.ts
Labels: lgtm, approved, qe-approved

#365 NETOBSERV-1113 implements RTT option in Console Plugin
  config/sample-frontend-config.yaml
  mocks/loki/flows.json
  pkg/handler/validation.go
  pkg/loki/filter.go
  pkg/loki/flow_query.go
  pkg/loki/topology_query.go
  pkg/model/fields/fields.go
  pkg/utils/constants/constants.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/ipfix.ts
  web/src/api/routes.ts
  web/src/components/__tests-data__/metrics.ts
  web/src/components/dropdowns/metric-function-dropdown.tsx
  web/src/components/dropdowns/metric-type-dropdown.tsx
  web/src/components/dropdowns/topology-display-dropdown.tsx
  web/src/components/filters/filters-dropdown.tsx
  web/src/components/filters/filters-helper.ts
  web/src/components/filters/filters-toolbar.tsx
  web/src/components/metrics/metrics-content.tsx
  web/src/components/netflow-overview/__tests__/netflow-overview.spec.tsx
  web/src/components/netflow-overview/netflow-overview-panel.tsx
  web/src/components/netflow-overview/netflow-overview.css
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-topology/__tests-data__/metrics.ts
  web/src/components/netflow-topology/element-panel-metrics.tsx
  web/src/components/netflow-topology/element-panel-stats.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/metrics-query-summary.tsx
  web/src/components/query-summary/summary-panel.tsx
  web/src/model/config.ts
  web/src/model/filters.ts
  web/src/model/flow-query.ts
  web/src/utils/__tests__/metrics.spec.ts
  web/src/utils/columns.ts
  web/src/utils/duration.ts
  web/src/utils/filter-definitions.ts
  web/src/utils/metrics.ts
  web/src/utils/overview-panels.ts
Labels: lgtm, approved, ok-to-test

#375 NETOBSERV-967 skip ticks when popups are open
  web/cypress/e2e/overview/overview.spec.ts
  web/cypress/e2e/table/table.spec.ts
  web/cypress/e2e/topology/topology.spec.ts
  web/cypress/support/commands.ts
  web/cypress/support/const.ts
  web/src/components/modals/columns-modal.tsx
  web/src/components/modals/overview-panels-modal.tsx
  web/src/components/netflow-traffic.tsx
Labels: lgtm, approved, qe-approved

#381 NETOBSERV-1113 fix pktDrop & FlowRTT merge
  web/src/components/netflow-traffic.tsx
  web/src/utils/filter-definitions.ts
Labels: no-qe, lgtm, approved

#382 update ovs_drop_last_action doc
  web/src/utils/pkt-drop.ts
Labels: no-qe, lgtm, approved, no-doc

#378 NETOBSERV-1275: Introduce new "INNER" direction for inner-node traffic
  pkg/model/filters/filters.go
  pkg/model/filters/filters_test.go
  pkg/server/server_test.go
  pkg/utils/constants/constants.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/ipfix.ts
  web/src/components/dropdowns/query-options-dropdown.tsx
  web/src/components/netflow-record/record-field.tsx
  web/src/utils/columns.ts
  web/src/utils/filter-definitions.ts
  web/src/utils/filter-options.ts
  web/src/utils/flows.ts
Labels: lgtm, approved, jira/valid-reference

#387 NETOBSERV-1222: create PR template
  .github/pull_request_template.md
Labels: lgtm, approved, jira/valid-reference

#384 NETOBSERV-1299 missing DNS latency in topology & NETOBSERV-1294 RTT based panels seen by default
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/dropdowns/metric-function-dropdown.tsx
  web/src/components/dropdowns/metric-type-dropdown.tsx
  web/src/components/dropdowns/topology-display-dropdown.tsx
  web/src/components/metrics/metrics-content.tsx
  web/src/components/netflow-topology/element-panel-metrics.tsx
  web/src/components/netflow-topology/element-panel-stats.tsx
  web/src/components/netflow-traffic.tsx
Labels: lgtm, approved, qe-approved, ok-to-test

#388 [Backport] NETOBSERV-1299 & NETOBSERV-1294
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/dropdowns/metric-function-dropdown.tsx
  web/src/components/dropdowns/metric-type-dropdown.tsx
  web/src/components/dropdowns/topology-display-dropdown.tsx
  web/src/components/metrics/metrics-content.tsx
  web/src/components/netflow-topology/element-panel-metrics.tsx
  web/src/components/netflow-topology/element-panel-stats.tsx
  web/src/components/netflow-traffic.tsx
Labels: lgtm, approved, qe-approved, ok-to-test

#383 Update flow model doc
  web/docs/README.md
  web/docs/enums/FlowDirection.md
  web/docs/enums/InterfaceDirection.md
  web/docs/interfaces/Fields.md
  web/src/api/ipfix.ts
Labels: lgtm, approved

#380 NETOBSERV-1274 index duplicate (improve query perfs)
  pkg/loki/flow_query.go
  web/src/api/ipfix.ts
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/query-summary/summary-panel.tsx
  web/src/utils/columns.ts
Labels: no-qe, lgtm, approved, no-doc
