Repository netobserv/network-observability-console-plugin, pull requests merged in 2024-04, with the labels that each got.

#512 codecov v4
  .github/workflows/pull_request.yml
  .github/workflows/push_image.yml
Labels: lgtm, approved

#511 Prior config refactoring before adding prometheus config
  cmd/plugin-backend.go
  pkg/config/config.go
  pkg/config/duration.go
  pkg/config/loki.go
  pkg/handler/csv/loki_csv.go
  pkg/handler/export.go
  pkg/handler/flows.go
  pkg/handler/frontend-config.go
  pkg/handler/loki.go
  pkg/handler/resources.go
  pkg/handler/resources_test.go
  pkg/handler/response.go
  pkg/handler/topology.go
  pkg/loki/config.go
  pkg/loki/flow_query.go
  pkg/loki/query_test.go
  pkg/loki/topology_query.go
  pkg/server/metrics_server.go
  pkg/server/routes.go
  pkg/server/server.go
  pkg/server/server_flows_test.go
  pkg/server/server_test.go
Labels: no-qe, lgtm, approved, ok-to-test, no-doc

#515 Codecov add env token from secret
  .github/workflows/pull_request.yml
  .github/workflows/push_image.yml
Labels: lgtm, approved

#518 NETOBSERV-1596 fix latest not resetting on DNS / RTT metrics
  web/src/model/flow-query.ts
Labels: lgtm, approved, qe-approved, ok-to-test
