Repository netobserv/network-observability-console-plugin, pull requests merged in 2024-11, with the labels that each got.

#607 backport : Addressing konflux error and fixing multi arch build with podman 5.2 …
  .snyk
  .tekton/network-observability-console-plugin-pull-request.yaml
  .tekton/network-observability-console-plugin-push.yaml
  .tekton/pipeline-ref.yaml
  Dockerfile
  Dockerfile.downstream
  Makefile
  hack/update-build.sh
Labels: lgtm, approved

#623 NETOBSERV-1885: fix resources/names endpoint
  config/sample-config.yaml
  pkg/server/routes.go
  web/src/api/routes.ts
  web/src/components/toolbar/filters-toolbar.tsx
Labels: lgtm, approved, qe-approved, ok-to-test, jira/valid-reference

#643 NETOBSERV-1958: fix CSV export
  web/src/model/__tests__/export-query.spec.ts
  web/src/model/export-query.ts
Labels: lgtm, approved, qe-approved, ok-to-test, jira/valid-reference

#596 Dockerfile cleanup: remove unused args
  Dockerfile
Labels: no-qe, no-doc

#634 NETOBSERV-1927 scopes config
  config/sample-config.yaml
  pkg/config/config.go
  pkg/handler/lokiclientmock/loki_client_mock.go
  pkg/handler/topology.go
  pkg/loki/topology_query.go
  pkg/loki/topology_query_test.go
  pkg/prometheus/query.go
  pkg/prometheus/query_test.go
  pkg/server/server_test.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/loki.ts
  web/src/api/routes.ts
  web/src/components/__tests-data__/scopes.ts
  web/src/components/drawer/element/element-fields.tsx
  web/src/components/drawer/element/element-panel-content.tsx
  web/src/components/drawer/netflow-traffic-drawer.tsx
  web/src/components/dropdowns/__tests__/group-dropdown.spec.tsx
  web/src/components/dropdowns/group-dropdown.tsx
  web/src/components/dropdowns/overview-display-dropdown.tsx
  web/src/components/dropdowns/overview-display-options.tsx
  web/src/components/dropdowns/scope-dropdown.tsx
  web/src/components/dropdowns/topology-display-dropdown.tsx
  web/src/components/dropdowns/topology-display-options.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/summary-panel-content.tsx
  web/src/components/slider/scope-slider.tsx
  web/src/components/slider/slider.tsx
  web/src/components/tabs/netflow-topology/2d/styles/styleDecorators.tsx
  web/src/components/tabs/netflow-topology/2d/topology-content.tsx
  web/src/components/tabs/netflow-topology/3d/three-d-topology-content.tsx
  web/src/components/tabs/netflow-topology/__tests__/netflow-topology.spec.tsx
  web/src/components/tabs/netflow-topology/netflow-topology.tsx
  web/src/components/toolbar/view-options-toolbar.tsx
  web/src/model/__tests__/topology.spec.ts
  web/src/model/config.ts
  web/src/model/flow-query.ts
  web/src/model/netflow-traffic.ts
  web/src/model/scope.ts
  web/src/model/topology.ts
  web/src/utils/__tests__/back-and-forth.spec.ts
  web/src/utils/__tests__/metrics.spec.ts
  web/src/utils/context.ts
  web/src/utils/ids.ts
  web/src/utils/metrics-helper.ts
  web/src/utils/metrics.ts
Labels: lgtm, ok-to-test

#646 Fixing source image tagging in konflux
  .tekton/pipeline-ref.yaml
Labels: lgtm, approved

#648 Fixing konflux pipeline results
  .tekton/pipeline-ref.yaml
Labels: lgtm, approved

#633 NETOBSERV-1959: Remove hardcoded columns rendering + other enhancements
  config/sample-config.yaml
  web/src/components/__tests-data__/columns.ts
  web/src/components/__tests-data__/flows.ts
  web/src/components/drawer/record/__tests__/record-field.spec.tsx
  web/src/components/drawer/record/__tests__/record-panel.spec.tsx
  web/src/components/drawer/record/record-field.tsx
  web/src/components/drawer/record/record-panel.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/__tests__/summary-panel.spec.tsx
  web/src/components/tabs/netflow-table/netflow-table-row.tsx
  web/src/utils/__tests__/columns.spec.ts
  web/src/utils/column-parser.ts
  web/src/utils/columns.ts
Labels: no-qe, no-doc, jira/valid-reference

#649 NETOBSERV-1951: show flows with networkevents 1st for duplicate flows
  web/src/utils/flows.ts
Labels: lgtm, approved, qe-approved, ok-to-test, jira/valid-reference

#651 Adding rmps scan task to konflux
  .tekton/pipeline-ref.yaml
Labels: lgtm, approved

#650 Fix Uncaught TypeError: e.currentTarget.children[0] is undefined
  web/src/components/drawer/record/record-field.tsx
Labels: no-qe, lgtm, approved, no-doc

#652 Fixing build version during image build
  .tekton/pipeline-ref.yaml
  Dockerfile.downstream
Labels: lgtm, approved

#632 NETOBSERV-1890: read TCP flags as strings
  pkg/model/fields/fields.go
  web/src/api/ipfix.ts
  web/src/components/drawer/record/record-field.tsx
  web/src/utils/__tests__/tcp-flags.spec.ts
  web/src/utils/filter-options.ts
  web/src/utils/tcp-flags.ts
Labels: lgtm, approved, qe-approved, ok-to-test, jira/valid-reference

#659 Fix version in konflux build
  .tekton/pipeline-ref.yaml
  Dockerfile.downstream
Labels: lgtm, approved
