Repository netobserv/network-observability-console-plugin, pull requests merged in 2024-06, with the labels that each got.

#533 NETOBSERV-1630 allow not for ip filters
  pkg/loki/flow_query.go
  pkg/model/filters/logql.go
Labels: lgtm, approved, qe-approved, ok-to-test

#537 Backport of NETOBSERV-1630
  pkg/loki/flow_query.go
  pkg/model/filters/logql.go
Labels: lgtm, approved

#539 Backport of NETOBSERV-1621
  config/sample-config.yaml
  pkg/kubernetes/auth/check_auth.go
  pkg/kubernetes/auth/check_auth_test.go
  pkg/server/routes.go
  pkg/server/server_test.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/messages/error.css
  web/src/components/messages/error.tsx
  web/src/components/messages/prometheus-unsupported.tsx
  web/src/components/netflow-overview/__tests__/netflow-overview.spec.tsx
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-tab.tsx
  web/src/components/netflow-table/__tests__/netflow-table.spec.tsx
  web/src/components/netflow-table/netflow-table.css
  web/src/components/netflow-table/netflow-table.tsx
  web/src/components/netflow-topology/__tests__/netflow-topology.spec.tsx
  web/src/components/netflow-topology/netflow-topology.css
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/config.ts
  web/src/utils/config.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#523 NETOBSERV-1621: fix error messages
  config/sample-config.yaml
  pkg/kubernetes/auth/check_auth.go
  pkg/kubernetes/auth/check_auth_test.go
  pkg/server/routes.go
  pkg/server/server_test.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/messages/error.css
  web/src/components/messages/error.tsx
  web/src/components/messages/prometheus-unsupported.tsx
  web/src/components/netflow-overview/__tests__/netflow-overview.spec.tsx
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-tab.tsx
  web/src/components/netflow-table/__tests__/netflow-table.spec.tsx
  web/src/components/netflow-table/netflow-table.css
  web/src/components/netflow-table/netflow-table.tsx
  web/src/components/netflow-topology/__tests__/netflow-topology.spec.tsx
  web/src/components/netflow-topology/netflow-topology.css
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/config.ts
  web/src/utils/config.ts
Labels: lgtm, approved, qe-approved, ok-to-test, jira/valid-reference

#542 NETOBSERV-1707: move to go 1.22
  .github/workflows/pull_request.yml
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  .golangci.yml
  Dockerfile
  Dockerfile.ci
  Dockerfile.cypress
  web/src/components/messages/error.tsx
Labels: no-qe, lgtm, approved, no-doc, jira/valid-reference

#540 NETOBSERV-1649: remove obsolete comment
  pkg/handler/topology.go
Labels: lgtm, approved, jira/valid-reference

#547 Add .ci-operator.yaml
  .ci-operator.yaml
Labels: lgtm

#550 NETOBSERV-1720: fix issues with topology scopes
  web/src/components/netflow-topology/2d/topology-content.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/topology.ts
Labels: approved, qe-approved, ok-to-test, jira/valid-reference
