Repository netobserv/network-observability-console-plugin, pull requests merged in 2024-03, with the labels that each got.

#486 NETOBSERV-1520 Create plugin CI and cypress configs
  .gitignore
  .mk/ci.mk
  .mk/cypress.mk
  .mk/shortcuts.mk
  .mk/standalone.mk
  Dockerfile.ci
  Dockerfile.cypress
  Makefile
  scripts/cypress.sh
  web/cypress/e2e/table/table.spec.ts
  web/cypress/support/commands.ts
  web/package-lock.json
  web/package.json
Labels: lgtm, approved

#476 NETOBSERV-1503 Console plugin fields config
  config/sample-config.yaml
  pkg/handler/config.go
  web/src/api/routes.ts
  web/src/components/__tests-data__/columns.ts
  web/src/components/__tests-data__/config.ts
  web/src/components/modals/columns-modal.tsx
  web/src/components/modals/export-modal.tsx
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/config.ts
  web/src/utils/columns.ts
  web/src/utils/fields.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#482 NETOBSERV-1466 NodeDirections / IfDirections
  config/sample-config.yaml
  pkg/handler/topology.go
  pkg/loki/filter.go
  pkg/loki/flow_query.go
  pkg/model/fields/fields.go
  pkg/server/server_test.go
  web/docs/enums/NodeDirection.md
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/ipfix.ts
  web/src/components/netflow-record/__tests__/record-panel.spec.tsx
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/columns.ts
  web/src/utils/filter-definitions.ts
  web/src/utils/filter-options.ts
Labels: lgtm, approved, breaking-change

#497 NETOBSERV-1514: drop go1.20 support
  .github/workflows/pull_request.yml
  go.mod
  go.sum
Labels: lgtm, approved, jira/valid-reference

#498 update config
  .gitignore
  config/sample-config.yaml
  scripts/update-config.sh
Labels: lgtm, approved

#500 fix cypress: added 1 column
  web/cypress/support/const.ts
Labels: lgtm, approved

#499 NETOBSERV-1466 rely on duplicate different than 'true'
  mocks/updateMocks.sh
  pkg/loki/filter.go
  pkg/loki/flow_query.go
  pkg/server/server_flows_test.go
  pkg/server/server_test.go
Labels: lgtm, approved, ok-to-test

#489 NETOBSERV-1551: show cross-nodes duplicates in merge mode
  web/src/utils/__tests__/flows.spec.ts
  web/src/utils/columns.ts
  web/src/utils/flows.ts
Labels: approved, qe-approved, ok-to-test, jira/valid-reference

#505 NETOBSERV-1575: Upgrade to node18, bump some libs
  .github/workflows/pull_request.yml
  .github/workflows/push_image.yml
  Dockerfile
  Dockerfile.cypress
  Makefile
  web/package-lock.json
  web/package.json
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#431 NETOBSERV-1382 - Custom metrics from config
  config/sample-config.yaml
  pkg/handler/config.go
  pkg/handler/topology.go
  pkg/handler/validation.go
  pkg/handler/validation_test.go
  pkg/loki/flow_query.go
  pkg/loki/topology_query.go
  pkg/server/server_test.go
  pkg/utils/constants/constants.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/ipfix.ts
  web/src/api/loki.ts
  web/src/api/routes.ts
  web/src/components/__tests-data__/config.ts
  web/src/components/__tests-data__/panels.ts
  web/src/components/__tests__/netflow-traffic.spec.tsx
  web/src/components/dropdowns/__tests__/metric-type-dropdown.spec.tsx
  web/src/components/dropdowns/metric-function-dropdown.tsx
  web/src/components/dropdowns/metric-type-dropdown.tsx
  web/src/components/dropdowns/topology-display-dropdown.tsx
  web/src/components/metrics/__tests__/metrics-donut.spec.tsx
  web/src/components/metrics/__tests__/metrics-graph.spec.tsx
  web/src/components/metrics/histogram.tsx
  web/src/components/metrics/metrics-donut.tsx
  web/src/components/metrics/metrics-graph-total.tsx
  web/src/components/modals/__tests__/overview-panels-modal.spec.tsx
  web/src/components/modals/overview-panels-modal.tsx
  web/src/components/netflow-overview/__tests__/netflow-overview-panel.spec.tsx
  web/src/components/netflow-overview/__tests__/netflow-overview.spec.tsx
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-table/__tests__/netflow-table.spec.tsx
  web/src/components/netflow-topology/2d/topology-content.tsx
  web/src/components/netflow-topology/3d/three-d-topology-content.tsx
  web/src/components/netflow-topology/__tests__/element-panel.spec.tsx
  web/src/components/netflow-topology/__tests__/netflow-topology.spec.tsx
  web/src/components/netflow-topology/element-panel-metrics.tsx
  web/src/components/netflow-topology/element-panel-stats.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/__tests__/flows-query-summary.spec.tsx
  web/src/components/query-summary/metrics-query-summary.tsx
  web/src/components/query-summary/summary-panel.tsx
  web/src/model/config.ts
  web/src/model/flow-query.ts
  web/src/model/metrics.ts
  web/src/model/topology.ts
  web/src/utils/__tests__/metrics.spec.ts
  web/src/utils/__tests__/protocol.spec.ts
  web/src/utils/local-storage-hook.ts
  web/src/utils/metrics.ts
  web/src/utils/overview-panels.ts
  web/src/utils/protocol.ts
  web/src/utils/router.ts
Labels: lgtm, approved, qe-approved, ok-to-test
