Repository netobserv/network-observability-console-plugin, pull requests merged in 2024-05, with the labels that each got.

#526 Remove references to *handshake* RTT (it's sRTT)
  config/sample-config.yaml
  web/docs/interfaces/Fields.md
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/ipfix.ts
  web/src/components/__tests-data__/columns.ts
  web/src/components/__tests-data__/filters.ts
  web/src/utils/overview-panels.ts
Labels: no-qe, lgtm, approved

#530 disable color codes
  scripts/cypress.sh
Labels: lgtm, approved

#531 Codecov: remove token, turn off CI failure
  .github/workflows/greetings.yml
  .github/workflows/pull_request.yml
Labels: no-qe, no-doc
