Repository netobserv/network-observability-console-plugin, pull requests merged in 2024-07, with the labels that each got.

#549 NETOBSERV-1649: Improve UX and cases managed with prometheus
  pkg/model/fields/fields.go
  pkg/prometheus/inventory.go
  pkg/prometheus/inventory_test.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/messages/error.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/flows-query-summary-content.tsx
  web/src/components/query-summary/flows-query-summary.tsx
  web/src/components/query-summary/metrics-query-summary-content.tsx
  web/src/components/query-summary/metrics-query-summary.tsx
  web/src/components/query-summary/stats-query-summary.tsx
  web/src/components/query-summary/summary-panel-content.tsx
  web/src/components/query-summary/summary-panel.tsx
  web/src/model/warnings.ts
Labels: qe-approved, jira/valid-reference

#563 NETOBSERV-1733 fix url filters init / update
  web/cypress/e2e/table/table.spec.ts
  web/src/components/netflow-traffic.tsx
  web/src/utils/url.ts
Labels: lgtm, approved, qe-approved

#570 Removed base image ref in konflux
  .tekton/network-observability-console-plugin-pull-request.yaml
  .tekton/network-observability-console-plugin-push.yaml
Labels: lgtm, approved

#562 NETOBSERV-1540 fix panels filter chips
  web/src/components/modals/__tests__/overview-panels-modal.spec.tsx
  web/src/components/modals/modals.tsx
  web/src/components/modals/overview-panels-modal.tsx
Labels: lgtm, approved, qe-approved, ok-to-test

#558 NETOBSERV-1764 Frontend code styling follow-up
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/drawer/netflow-traffic-drawer.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/tabs/netflow-overview/netflow-overview.tsx
  web/src/components/tabs/netflow-table/netflow-table.tsx
  web/src/components/tabs/netflow-topology/netflow-topology.tsx
Labels: lgtm, approved, qe-approved, ok-to-test
