Repository netobserv/network-observability-console-plugin, pull requests merged in 2024-08, with the labels that each got.

#554 NETOBSERV-1756 Allow filtering based on TCPFlags values
  pkg/model/fields/fields.go
  web/src/components/drawer/record/record-field.tsx
  web/src/utils/columns.ts
  web/src/utils/filter-definitions.ts
  web/src/utils/filter-options.ts
  web/src/utils/tcp_flags.ts
Labels: lgtm, approved, ok-to-test

#576 automate standalone build
  .github/workflows/push_image.yml
Labels: no-qe, lgtm, approved, no-doc

#571 NETOBSERV-1689 Allow multi-tenant Prometheus queries
  pkg/config/config.go
  pkg/handler/clients.go
  pkg/handler/flows.go
  pkg/handler/resources.go
  pkg/handler/topology.go
  pkg/handler/topology_test.go
  pkg/model/filters/filters.go
  pkg/model/filters/filters_test.go
  pkg/model/filters/logql.go
  pkg/prometheus/client.go
  web/console-extensions.json
  web/locales/en/plugin__netobserv-plugin.json
  web/package.json
  web/src/app.tsx
  web/src/components/netflow-traffic-dev-tab.tsx
  web/src/components/netflow-traffic-parent.tsx
  web/src/components/netflow-traffic-tab.tsx
  web/src/components/netflow-traffic.css
  web/src/components/netflow-traffic.tsx
  web/src/components/tabs/tabs-container.tsx
  web/src/components/toolbar/filters-toolbar.css
  web/src/model/flow-query.ts
Labels: lgtm, approved, qe-approved, ok-to-test
