Repository netobserv/network-observability-console-plugin, pull requests merged in 2024-12, with the labels that each got.

#661 NETOBSERV-1990: fix NOT filters with multiple values
  .golangci.yml
  pkg/loki/flow_query.go
  pkg/model/filters/logql.go
  pkg/model/filters/logql_test.go
  pkg/server/server_flows_test.go
  web/src/model/__tests__/filters.spec.ts
Labels: lgtm, qe-approved, ok-to-test, jira/valid-reference

#657 NETOBSERV-1927 fix topology issues
  web/src/model/topology.ts
  web/src/utils/metrics.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#604 NETOBSERV-1814 add cypress checks on fields
  config/sample-config.yaml
  mocks/loki/flow_records.json
  pkg/config/config.go
  web/cypress/e2e/table/fields.spec.ts
  web/cypress/support/commands.ts
  web/cypress/support/const.ts
  web/src/components/tabs/netflow-table/netflow-table-row.tsx
  web/src/components/tabs/netflow-table/netflow-table.tsx
  web/src/model/config.ts
  web/src/utils/icmp.ts
Labels: no-qe, lgtm, approved

#621 NETOBSERV-1580 add update-config target
  Makefile
  config/sample-config.yaml
  web/src/components/drawer/record/record-field.tsx
  web/src/components/drawer/record/record-panel.tsx
  web/src/utils/columns.ts
Labels: lgtm, approved

#673 Adding version label in downstream image
  Dockerfile.downstream
Labels: lgtm, approved
