Repository netobserv/network-observability-console-plugin, pull requests merged in 2024-10, with the labels that each got.

#608 Bump rollup from 3.5.0 to 3.29.5 in /web [1.7 backport]
  web/package-lock.json
Labels: approved

#610 NETOBSERV-1920: slider: switch to abbreviated mode with small screens
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/slider/scope-slider.css
  web/src/components/slider/scope-slider.tsx
  web/src/components/slider/slider.tsx
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#613 NETOBSERV-1920: slider: switch to abbreviated mode with small screens [1.7 backport]
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/slider/scope-slider.css
  web/src/components/slider/scope-slider.tsx
  web/src/components/slider/slider.tsx
Labels: jira/valid-reference

#612 NETOBSERV-1914 backport
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/messages/status-texts.tsx
Labels: lgtm, approved, qe-approved, ok-to-test

#611 NETOBSERV-1914 improved status message
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/messages/status-texts.tsx
Labels: lgtm, approved, qe-approved, ok-to-test

#617 Fix error logs/message for loki-op 6
  pkg/handler/loki.go
Labels: no-qe, no-doc

#615 NETOBSERV-1871 First request to get flow data waits indefinitely on workloads network-traffic page
  web/src/components/netflow-traffic.tsx
Labels: lgtm, approved, qe-approved, ok-to-test

#618 Fix error logs/message for loki-op 6 [1.7 backport]
  pkg/handler/loki.go
Labels: no-qe

#619 Distinguish "clean builds" and dev builds
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  Dockerfile
  Makefile
Labels: no-qe, lgtm, approved, no-doc
