Repository netobserv/network-observability-console-plugin, pull requests merged in 2024-01, with the labels that each got.

#448 NETOBSERV-1445: update deps
  web/package-lock.json
  web/package.json
Labels: no-qe, lgtm, approved, no-doc, jira/valid-reference

#449 Improve TCP flags doc
  web/src/api/ipfix.ts
Labels: no-qe, lgtm, approved, no-doc

#451 NETOBSERV-1451: Bump ubi 9.3 / go 1.21
  .github/workflows/pull_request.yml
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  .golangci.yml
  Dockerfile
  go.mod
  pkg/server/server_test.go
Labels: no-qe, lgtm, approved, no-doc, jira/valid-reference

#454 NETOBSERV-1429 Netflow tab crash followup
  web/src/components/netflow-tab.tsx
  web/src/components/netflow-traffic-parent.tsx
  web/src/components/netflow-traffic.tsx
Labels: lgtm, approved, qe-approved, ok-to-test

#455 Packet drop message update
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/dropdowns/query-options-dropdown.tsx
Labels: no-qe, lgtm, approved, no-doc

#435 NETOBSERV-1407 console deduper merge mode
  cmd/plugin-backend.go
  config/sample-config.yaml
  mocks/loki/flow_records.json
  pkg/handler/config.go
  pkg/handler/flows.go
  pkg/handler/topology.go
  pkg/loki/config.go
  pkg/loki/filter.go
  pkg/loki/flow_query.go
  pkg/loki/query_test.go
  pkg/loki/topology_query.go
  pkg/server/server_flows_test.go
  pkg/server/server_test.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/ipfix.ts
  web/src/api/routes.ts
  web/src/components/__tests-data__/config.ts
  web/src/components/dropdowns/__tests__/query-options-dropdown.spec.tsx
  web/src/components/dropdowns/query-options-dropdown.tsx
  web/src/components/filters/__tests__/filters-toolbar.spec.tsx
  web/src/components/netflow-record/__tests__/record-panel.spec.tsx
  web/src/components/netflow-record/record-field.tsx
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-table/netflow-table-header.tsx
  web/src/components/netflow-traffic.tsx
  web/src/model/config.ts
  web/src/utils/columns.ts
  web/src/utils/flows.ts
Labels: no-qe, lgtm, approved

#460 Add duration tests
  web/src/utils/__tests__/duration.spec.ts
Labels: no-qe, lgtm, approved, no-doc

#438 NETOBSERV-1285 Move "query is slow" info to query summary
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/netflow-overview/netflow-overview.tsx
  web/src/components/netflow-table/netflow-table.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/__tests__/summary-panel.spec.tsx
  web/src/components/query-summary/flows-query-summary.tsx
  web/src/components/query-summary/metrics-query-summary.tsx
  web/src/components/query-summary/query-summary.css
  web/src/components/query-summary/stats-query-summary.tsx
  web/src/components/query-summary/summary-panel.tsx
Labels: lgtm, approved

#446 NETOBSERV-1443 Console plugin loki timeout should be configurable
  pkg/server/server.go
Labels: lgtm, approved, ok-to-test

#450 NETOBSERV-1450: use isolated states for mobx
  web/package-lock.json
  web/package.json
  web/src/index.tsx
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#445 NETOBSERV-792: flag recent metrics as "inaccurate"
  pkg/handler/loki.go
  pkg/server/routes.go
  web/locales/en/plugin__netobserv-plugin.json
  web/package-lock.json
  web/package.json
  web/src/api/routes.ts
  web/src/components/modals/__tests__/time-range-modal.spec.tsx
  web/src/components/modals/time-range-modal.css
  web/src/components/modals/time-range-modal.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/query-summary/__tests__/summary-panel.spec.tsx
  web/src/components/query-summary/summary-panel.tsx
  web/src/utils/config.ts
  web/src/utils/duration.ts
Labels: lgtm, approved, jira/valid-reference

#459 NETOBSERV-1355 autocomplete menu button
  web/src/components/filters/autocomplete-filter.css
  web/src/components/filters/autocomplete-filter.tsx
  web/src/utils/filter-definitions.ts
  web/src/utils/filter-options.ts
Labels: lgtm, approved, ok-to-test

#424 NETOBSERV-267 Panels & columns popup filters
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/filters/filters-toolbar.css
  web/src/components/modals/columns-modal.css
  web/src/components/modals/columns-modal.tsx
  web/src/components/modals/export-modal.tsx
  web/src/components/modals/overview-panels-modal.css
  web/src/components/modals/overview-panels-modal.tsx
Labels: lgtm, approved, ok-to-test

#461 NETOBSERV-1464: help on 'input size too long'
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/messages/loki-error.tsx
Labels: lgtm, approved, jira/valid-reference

#464 NETOBSERV-1214 & NETOBSERV-1399 Backport
  config/sample-config.yaml
  mocks/updateMocks.sh
  pkg/handler/config.go
  pkg/handler/lokiclientmock/loki_client_mock.go
  pkg/handler/resources.go
  pkg/loki/topology_query.go
  pkg/model/fields/fields.go
  pkg/server/routes.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/ipfix.ts
  web/src/api/loki.ts
  web/src/api/routes.ts
  web/src/components/dropdowns/__tests__/group-dropdown.spec.tsx
  web/src/components/dropdowns/group-dropdown.tsx
  web/src/components/dropdowns/overview-display-dropdown.tsx
  web/src/components/dropdowns/scope-dropdown.tsx
  web/src/components/dropdowns/topology-display-dropdown.tsx
  web/src/components/filters/summary-filter-button.tsx
  web/src/components/metrics/metrics-helper.tsx
  web/src/components/netflow-record/record-panel.tsx
  web/src/components/netflow-topology/2d/styles/styleDecorators.tsx
  web/src/components/netflow-topology/2d/styles/styleNode.tsx
  web/src/components/netflow-topology/2d/topology-content.tsx
  web/src/components/netflow-topology/__tests__/netflow-topology.spec.tsx
  web/src/components/netflow-topology/element-fields.tsx
  web/src/components/netflow-topology/element-panel.tsx
  web/src/components/netflow-topology/netflow-topology.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/scope-slider/scope-slider.css
  web/src/components/scope-slider/scope-slider.tsx
  web/src/model/config.ts
  web/src/model/filters.ts
  web/src/model/flow-query.ts
  web/src/model/metrics.ts
  web/src/model/topology.ts
  web/src/utils/autocomplete-cache.ts
  web/src/utils/columns.ts
  web/src/utils/filter-definitions.ts
  web/src/utils/filter-options.ts
  web/src/utils/ids.ts
  web/src/utils/metrics.ts
Labels: lgtm, approved
