Repository netobserv/network-observability-console-plugin, pull requests merged in 2025-02, with the labels that each got.

#705 [Backport] NETOBSERV-2049: Console table rows height are inconsistent
  web/src/components/drawer/record/record-field.css
  web/src/components/drawer/record/record-field.tsx
Labels: lgtm, approved, jira/valid-reference

#708 nit: nolint max-len
  web/src/components/drawer/record/record-panel.tsx
Labels: lgtm

#709 Release-1.8 : Reenabling ppc64le build
  .tekton/network-observability-console-plugin-1-8-pull-request.yaml
  .tekton/network-observability-console-plugin-1-8-push.yaml
Labels: lgtm, approved

#701 fix cypress column count
  config/sample-config.yaml
  web/cypress/support/const.ts
Labels: lgtm

#718 Konflux building frontend only once
  .tekton/pipeline-ref.yaml
  Dockerfile.downstream
  Dockerfile.front.downstream
Labels: lgtm, approved

#707 Avoid redundant frontend builds
  Dockerfile
  Dockerfile.front
  Makefile
Labels: lgtm

#722 backport: Building frontend only once (#718)
  .tekton/network-observability-console-plugin-1-8-pull-request.yaml
  .tekton/network-observability-console-plugin-1-8-push.yaml
  .tekton/pipeline-ref.yaml
  Dockerfile.downstream
  Dockerfile.front.downstream
Labels: lgtm, approved

#726 FIPS compliance [backport 1.8]
  Dockerfile.downstream
Labels: lgtm, approved

#725 FIPS compliance
  Dockerfile.downstream
Labels: lgtm, approved

#729 WIP Revert "Building frontend only once (#718) (#722)"
  .tekton/pipeline-ref.yaml
  Dockerfile.downstream
  Dockerfile.front.downstream
Labels: do-not-merge/work-in-progress
