Repository netobserv/network-observability-console-plugin, pull requests merged in 2025-05, with the labels that each got.

#688 NETOBSERV-1905 Query UDNs without flows
  pkg/handler/k8s.go
  pkg/kubernetes/auth/check_auth.go
  pkg/kubernetes/resources/resources.go
  pkg/server/routes.go
  vendor/k8s.io/client-go/dynamic/interface.go
  vendor/k8s.io/client-go/dynamic/scheme.go
  vendor/k8s.io/client-go/dynamic/simple.go
  vendor/modules.txt
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/routes.ts
  web/src/components/drawer/element/element-panel-content.tsx
  web/src/components/drawer/element/element-panel.tsx
  web/src/components/drawer/netflow-traffic-drawer.tsx
  web/src/components/dropdowns/topology-display-options.tsx
  web/src/components/netflow-traffic.tsx
  web/src/components/tabs/netflow-topology/2d/styles/styleNode.tsx
  web/src/components/tabs/netflow-topology/2d/topology-content.tsx
  web/src/components/tabs/netflow-topology/__tests__/netflow-topology.spec.tsx
  web/src/components/tabs/netflow-topology/netflow-topology.tsx
  web/src/model/netflow-traffic.ts
  web/src/model/topology.ts
Labels: qe-approved, ok-to-test

#837 NETOBSERV-2233 Make IPSec filters visible if feature is enabled
  web/src/components/netflow-traffic.tsx
  web/src/model/config.ts
  web/src/model/filters.ts
Labels: approved, qe-approved, needs-review

#844 NETOBSERV-2239: fix sorting by packets/bytes
  web/src/components/tabs/netflow-table/netflow-table.tsx
  web/src/utils/columns.ts
Labels: lgtm, qe-approved, ok-to-test, jira/valid-reference

#845 Allow custom registry
  Makefile
Labels: lgtm

#846 NETOBSERV-2227: UDN adjustments, and auto-detect filters
  pkg/config/config.go
  pkg/handler/k8s.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/__tests-data__/columns.ts
  web/src/components/__tests-data__/filters.ts
  web/src/components/drawer/record/record-field.tsx
  web/src/components/netflow-traffic.tsx
  web/src/utils/__tests__/filter-definitions.spec.ts
  web/src/utils/fields.ts
  web/src/utils/filter-definitions.ts
Labels: lgtm, qe-approved, ok-to-test, jira/valid-reference, needs-review

#847 NETOBSERV-2244: show topology when expectedNodes is set
  web/src/components/tabs/netflow-topology/2d/topology-content.tsx
  web/src/model/topology.ts
Labels: lgtm, qe-approved, ok-to-test, jira/valid-reference

#870 Fix ipsec column considered as IP
  web/src/utils/columns.ts
Labels: lgtm, approved, ok-to-test, needs-review
