Repository netobserv/network-observability-console-plugin, pull requests merged in 2025-03, with the labels that each got.

#755 NETOBSERV-2104 Filters in UI are visible despite features are disabled
  web/src/components/netflow-traffic.tsx
  web/src/model/config.ts
  web/src/model/filters.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#757 bump-1.9.0
  Dockerfile.downstream
Labels: lgtm, approved

#756 NETOBSERV-2119: use word-break break-all
  web/src/components/drawer/record/record-field.css
Labels: lgtm, qe-approved, ok-to-test, jira/valid-reference

#754 NETOBSERV-2139 remove observe menu entry
  web/console-extensions.json
Labels: lgtm, qe-approved

#768 NETOBSERV-2150: add license to downstream container
  .tekton/network-observability-console-plugin-pull-request.yaml
  .tekton/network-observability-console-plugin-push.yaml
  .tekton/pipeline-ref.yaml
  Dockerfile-args.downstream
  Dockerfile.downstream
Labels: no-qe, no-doc, jira/valid-reference

#778 NETOBSERV-2139 backport
  web/console-extensions.json
Labels: lgtm
