Repository netobserv/network-observability-console-plugin, pull requests merged in 2025-01, with the labels that each got.

#680 NETOBSERV-2056: Add xlat filters to hardcode fields list
  pkg/model/fields/fields.go
Labels: lgtm, approved, qe-approved, ok-to-test, jira/valid-reference

#656 NETOBSERV-1902 Additionnal graphs + tab + autocomplete for UDN
  config/sample-config.yaml
  mocks/loki/flow_metrics_dropped_udn.json
  mocks/loki/flow_metrics_udn.json
  mocks/loki/flow_records.json
  mocks/loki/flow_records_has_dropped.json
  mocks/loki/flow_records_sent.json
  pkg/handler/lokiclientmock/loki_client_mock.go
  pkg/handler/resources.go
  pkg/model/fields/fields.go
  pkg/server/routes.go
  scripts/update-config.sh
  web/console-extensions.json
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/ipfix.ts
  web/src/api/loki.ts
  web/src/api/routes.ts
  web/src/app.tsx
  web/src/components/drawer/element/element-panel-content.tsx
  web/src/components/drawer/record/record-field.tsx
  web/src/utils/autocomplete-cache.ts
  web/src/utils/columns.ts
  web/src/utils/filter-definitions.ts
  web/src/utils/filter-options.ts
Labels: no-qe, lgtm, approved

#662 NETOBSERV-1977 automatically disable filters when not available in prometheus
  pkg/handler/response.go
  pkg/handler/topology.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/drawer/netflow-traffic-drawer.tsx
  web/src/components/messages/error.tsx
  web/src/components/netflow-traffic.css
  web/src/components/netflow-traffic.tsx
  web/src/components/tabs/netflow-topology/netflow-topology.tsx
  web/src/components/toolbar/filters/chips-popover.tsx
  web/src/model/netflow-traffic.ts
  web/src/utils/errors.ts
Labels: lgtm, approved, qe-approved, ok-to-test

#696 NETOBSERV-1991 remove 3D topology to avoid blob creation
  web/locales/en/plugin__netobserv-plugin.json
  web/package-lock.json
  web/package.json
  web/src/components/tabs/netflow-topology/3d/three-d-topology-content.css
  web/src/components/tabs/netflow-topology/3d/three-d-topology-content.tsx
  web/src/components/tabs/netflow-topology/netflow-topology.tsx
Labels: lgtm, approved, qe-approved, ok-to-test

#681 NETOBSERV-2056 manage field types & formats from config
  config/sample-config.yaml
  pkg/config/config.go
  pkg/config/loki.go
  pkg/loki/flow_query.go
  pkg/model/fields/fields.go
  pkg/server/server_flows_test.go
  web/src/components/query-summary/summary-panel-content.tsx
  web/src/utils/column-parser.ts
  web/src/utils/fields.ts
Labels: lgtm, approved

#672 NETOBSERV-2004 Additionnal UI e2e tests for features columns
  config/sample-config.yaml
  mocks/loki/flow_records.json
  pkg/handler/lokiclientmock/loki_client_mock.go
  web/cypress/e2e/table/fields.spec.ts
  web/src/components/__tests-data__/flows.ts
Labels: lgtm, approved

#695 Manage IfDirection=3 (both)
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/ipfix.ts
Labels: approved

#698 NETOBSERV-1965: Add UDNs merger logic to merge udns accross nodes for the same flow
  pkg/model/fields/fields.go
  web/locales/en/plugin__netobserv-plugin.json
  web/src/api/ipfix.ts
  web/src/components/drawer/record/record-field.tsx
  web/src/utils/__tests__/flows.spec.ts
  web/src/utils/columns.ts
  web/src/utils/flows.ts
  web/src/utils/ids.ts
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#700 NETOBSERV-2049: Console table rows height are inconsistent
  web/src/components/drawer/record/record-field.css
  web/src/components/drawer/record/record-field.tsx
Labels: lgtm, qe-approved, ok-to-test, jira/valid-reference

#683 NETOBSERV-1992: explain partial flows
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/drawer/record/record-panel.css
  web/src/components/drawer/record/record-panel.tsx
Labels: lgtm, qe-approved, jira/valid-reference

#704 NETOBSERV-1992: explain partial flows [backport 1.8]
  web/locales/en/plugin__netobserv-plugin.json
  web/src/components/drawer/record/record-panel.css
  web/src/components/drawer/record/record-panel.tsx
Labels: lgtm, jira/valid-reference
